:doctype: book

+++<a id="lib-arrays">++++++</a>+++

+++<a id="lib-arrays-1">++++++</a>+++

= Arrays

+++<a id="Constructors-and-Types">++++++</a>+++

+++<a id="Constructors-and-Types-1">++++++</a>+++

== Constructors and Types

[id="Core.AbstractArray"]
==== *`Core.AbstractArray`* &mdash; _Type_.

[,julia]
----
AbstractArray{T,N}
----

Supertype for `N`-dimensional arrays (or array-like types) with elements of type `T`. xref:arrays.adoc#Core.Array[`Array`] and other types are subtypes of this. See the manual section on the xref:../manual/interfaces.adoc#man-interface-array[`AbstractArray` interface].

See also: xref:arrays.adoc#Base.AbstractVector[`AbstractVector`], xref:arrays.adoc#Base.AbstractMatrix[`AbstractMatrix`], xref:collections.adoc#Base.eltype[`eltype`], xref:arrays.adoc#Base.ndims[`ndims`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L5-L13[source] +

[id="Base.AbstractVector"]
==== *`Base.AbstractVector`* &mdash; _Type_.

[,julia]
----
AbstractVector{T}
----

Supertype for one-dimensional arrays (or array-like types) with elements of type `T`. Alias for xref:arrays.adoc#Core.AbstractArray[`AbstractArray{T,1}`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L17-L22[source] +

[id="Base.AbstractMatrix"]
==== *`Base.AbstractMatrix`* &mdash; _Type_.

[,julia]
----
AbstractMatrix{T}
----

Supertype for two-dimensional arrays (or array-like types) with elements of type `T`. Alias for xref:arrays.adoc#Core.AbstractArray[`AbstractArray{T,2}`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L25-L30[source] +

[id="Base.AbstractVecOrMat"]
==== *`Base.AbstractVecOrMat`* &mdash; _Type_.

[,julia]
----
AbstractVecOrMat{T}
----

Union type of xref:arrays.adoc#Base.AbstractVector[`+AbstractVector{T}+`] and xref:arrays.adoc#Base.AbstractMatrix[`+AbstractMatrix{T}+`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L33-L37[source] +

[id="Core.Array"]
==== *`Core.Array`* &mdash; _Type_.

[,julia]
----
Array{T,N} <: AbstractArray{T,N}
----

`N`-dimensional dense array with elements of type `T`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L45-L49[source] +

[id="Core.Array-Tuple{UndefInitializer, Any}"]
==== *`Core.Array`* &mdash; _Method_.

[,julia]
----
Array{T}(undef, dims)
Array{T,N}(undef, dims)
----

Construct an uninitialized `N`-dimensional xref:arrays.adoc#Core.Array[`Array`] containing elements of type `T`. `N` can either be supplied explicitly, as in `Array{T,N}(undef, dims)`, or be determined by the length or number of `dims`. `dims` may be a tuple or a series of integer arguments corresponding to the lengths in each dimension. If the rank `N` is supplied explicitly, then it must match the length or number of `dims`. Here xref:arrays.adoc#Core.undef[`undef`] is the xref:arrays.adoc#Core.UndefInitializer[`UndefInitializer`].

*Examples*

[,julia-repl]
----
julia> A = Array{Float64, 2}(undef, 2, 3) # N given explicitly
2×3 Matrix{Float64}:
 6.90198e-310  6.90198e-310  6.90198e-310
 6.90198e-310  6.90198e-310  0.0

julia> B = Array{Float64}(undef, 4) # N determined by the input
4-element Vector{Float64}:
   2.360075077e-314
 NaN
   2.2671131793e-314
   2.299821756e-314

julia> similar(B, 2, 4, 1) # use typeof(B), and the given size
2×4×1 Array{Float64, 3}:
[:, :, 1] =
 2.26703e-314  2.26708e-314  0.0           2.80997e-314
 0.0           2.26703e-314  2.26708e-314  0.0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2222-L2254[source] +

[id="Core.Array-Tuple{Nothing, Any}"]
==== *`Core.Array`* &mdash; _Method_.

[,julia]
----
Array{T}(nothing, dims)
Array{T,N}(nothing, dims)
----

Construct an `N`-dimensional xref:arrays.adoc#Core.Array[`Array`] containing elements of type `T`, initialized with xref:constants.adoc#Core.nothing[`nothing`] entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

*Examples*

[,julia-repl]
----
julia> Array{Union{Nothing, String}}(nothing, 2)
2-element Vector{Union{Nothing, String}}:
 nothing
 nothing

julia> Array{Union{Nothing, Int}}(nothing, 2, 3)
2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2257-L2277[source] +

[id="Core.Array-Tuple{Missing, Any}"]
==== *`Core.Array`* &mdash; _Method_.

[,julia]
----
Array{T}(missing, dims)
Array{T,N}(missing, dims)
----

Construct an `N`-dimensional xref:arrays.adoc#Core.Array[`Array`] containing elements of type `T`, initialized with xref:base.adoc#Base.missing[`missing`] entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

*Examples*

[,julia-repl]
----
julia> Array{Union{Missing, String}}(missing, 2)
2-element Vector{Union{Missing, String}}:
 missing
 missing

julia> Array{Union{Missing, Int}}(missing, 2, 3)
2×3 Matrix{Union{Missing, Int64}}:
 missing  missing  missing
 missing  missing  missing
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2281-L2301[source] +

[id="Core.UndefInitializer"]
==== *`Core.UndefInitializer`* &mdash; _Type_.

[,julia]
----
UndefInitializer
----

Singleton type used in array initialization, indicating the array-constructor-caller would like an uninitialized array. See also xref:arrays.adoc#Core.undef[`undef`], an alias for `UndefInitializer()`.

*Examples*

[,julia-repl]
----
julia> Array{Float64, 1}(UndefInitializer(), 3)
3-element Array{Float64, 1}:
 2.2752528595e-314
 2.202942107e-314
 2.275252907e-314
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2304-L2319[source] +

[id="Core.undef"]
==== *`Core.undef`* &mdash; _Constant_.

[,julia]
----
undef
----

Alias for `UndefInitializer()`, which constructs an instance of the singleton type xref:arrays.adoc#Core.UndefInitializer[`UndefInitializer`], used in array initialization to indicate the array-constructor-caller would like an uninitialized array.

See also: xref:base.adoc#Base.missing[`missing`], xref:arrays.adoc#Base.similar[`similar`].

*Examples*

[,julia-repl]
----
julia> Array{Float64, 1}(undef, 3)
3-element Vector{Float64}:
 2.2752528595e-314
 2.202942107e-314
 2.275252907e-314
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2322-L2339[source] +

[id="Base.Vector"]
==== *`Base.Vector`* &mdash; _Type_.

[,julia]
----
Vector{T} <: AbstractVector{T}
----

One-dimensional dense array with elements of type `T`, often used to represent a mathematical vector. Alias for xref:arrays.adoc#Core.Array[`Array{T,1}`].

See also xref:arrays.adoc#Base.empty[`empty`], xref:arrays.adoc#Base.similar[`similar`] and xref:numbers.adoc#Base.zero[`zero`] for creating vectors.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L52-L59[source] +

[id="Base.Vector-Tuple{UndefInitializer, Any}"]
==== *`Base.Vector`* &mdash; _Method_.

[,julia]
----
Vector{T}(undef, n)
----

Construct an uninitialized xref:arrays.adoc#Base.Vector[`+Vector{T}+`] of length `n`.

*Examples*

[,julia-repl]
----
julia> Vector{Float64}(undef, 3)
3-element Array{Float64, 1}:
 6.90966e-310
 6.90966e-310
 6.90966e-310
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2118-L2131[source] +

[id="Base.Vector-Tuple{Nothing, Any}"]
==== *`Base.Vector`* &mdash; _Method_.

[,julia]
----
Vector{T}(nothing, m)
----

Construct a xref:arrays.adoc#Base.Vector[`+Vector{T}+`] of length `m`, initialized with xref:constants.adoc#Core.nothing[`nothing`] entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

*Examples*

[,julia-repl]
----
julia> Vector{Union{Nothing, String}}(nothing, 2)
2-element Vector{Union{Nothing, String}}:
 nothing
 nothing
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2134-L2148[source] +

[id="Base.Vector-Tuple{Missing, Any}"]
==== *`Base.Vector`* &mdash; _Method_.

[,julia]
----
Vector{T}(missing, m)
----

Construct a xref:arrays.adoc#Base.Vector[`+Vector{T}+`] of length `m`, initialized with xref:base.adoc#Base.missing[`missing`] entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

*Examples*

[,julia-repl]
----
julia> Vector{Union{Missing, String}}(missing, 2)
2-element Vector{Union{Missing, String}}:
 missing
 missing
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2151-L2165[source] +

[id="Base.Matrix"]
==== *`Base.Matrix`* &mdash; _Type_.

[,julia]
----
Matrix{T} <: AbstractMatrix{T}
----

Two-dimensional dense array with elements of type `T`, often used to represent a mathematical matrix. Alias for xref:arrays.adoc#Core.Array[`Array{T,2}`].

See also xref:arrays.adoc#Base.fill[`fill`], xref:arrays.adoc#Base.zeros[`zeros`], xref:arrays.adoc#Core.undef[`undef`] and xref:arrays.adoc#Base.similar[`similar`] for creating matrices.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L62-L70[source] +

[id="Base.Matrix-Tuple{UndefInitializer, Any, Any}"]
==== *`Base.Matrix`* &mdash; _Method_.

[,julia]
----
Matrix{T}(undef, m, n)
----

Construct an uninitialized xref:arrays.adoc#Base.Matrix[`+Matrix{T}+`] of size `m`×`n`.

*Examples*

[,julia-repl]
----
julia> Matrix{Float64}(undef, 2, 3)
2×3 Array{Float64, 2}:
 2.36365e-314  2.28473e-314    5.0e-324
 2.26704e-314  2.26711e-314  NaN

julia> similar(ans, Int32, 2, 2)
2×2 Matrix{Int32}:
 490537216  1277177453
         1  1936748399
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2168-L2185[source] +

[id="Base.Matrix-Tuple{Nothing, Any, Any}"]
==== *`Base.Matrix`* &mdash; _Method_.

[,julia]
----
Matrix{T}(nothing, m, n)
----

Construct a xref:arrays.adoc#Base.Matrix[`+Matrix{T}+`] of size `m`×`n`, initialized with xref:constants.adoc#Core.nothing[`nothing`] entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

*Examples*

[,julia-repl]
----
julia> Matrix{Union{Nothing, String}}(nothing, 2, 3)
2×3 Matrix{Union{Nothing, String}}:
 nothing  nothing  nothing
 nothing  nothing  nothing
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2188-L2202[source] +

[id="Base.Matrix-Tuple{Missing, Any, Any}"]
==== *`Base.Matrix`* &mdash; _Method_.

[,julia]
----
Matrix{T}(missing, m, n)
----

Construct a xref:arrays.adoc#Base.Matrix[`+Matrix{T}+`] of size `m`×`n`, initialized with xref:base.adoc#Base.missing[`missing`] entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

*Examples*

[,julia-repl]
----
julia> Matrix{Union{Missing, String}}(missing, 2, 3)
2×3 Matrix{Union{Missing, String}}:
 missing  missing  missing
 missing  missing  missing
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2205-L2219[source] +

[id="Base.VecOrMat"]
==== *`Base.VecOrMat`* &mdash; _Type_.

[,julia]
----
VecOrMat{T}
----

Тестовый перевод для VecOrMat. Ссылка: xref:arrays.adoc#Base.Vector[`+Vector{T}+`]. Русский текст.

Вторая строка текста.

Третья строка текста.

Четвертая строка текста. Пробую два файла из папки.

*Примеры*

[,julia-repl]
----
julia> Vector{Float64} <: VecOrMat{Float64}
true

julia> Matrix{Float64} <: VecOrMat{Float64}
true

julia> Array{Float64, 3} <: VecOrMat{Float64}
false
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L73-L96[source] +

[id="Core.DenseArray"]
==== *`Core.DenseArray`* &mdash; _Type_.

[,julia]
----
DenseArray{T, N} <: AbstractArray{T,N}
----

Тестовый перевод для `DenseArray`. Русский текст.

Еще русский текст.

Английский текст оставлен как есть:

`N`-dimensional dense array with elements of type `T`. The elements of a dense array are stored contiguously in memory.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L92-L104[source] +

[id="Base.DenseVector"]
==== *`Base.DenseVector`* &mdash; _Type_.

[,julia]
----
DenseVector{T}
----

One-dimensional xref:arrays.adoc#Core.DenseArray[`DenseArray`] with elements of type `T`. Alias for `DenseArray{T,1}`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L100-L104[source] +

[id="Base.DenseMatrix"]
==== *`Base.DenseMatrix`* &mdash; _Type_.

[,julia]
----
DenseMatrix{T}
----

Two-dimensional xref:arrays.adoc#Core.DenseArray[`DenseArray`] with elements of type `T`. Alias for `DenseArray{T,2}`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L107-L111[source] +

[id="Base.DenseVecOrMat"]
==== *`Base.DenseVecOrMat`* &mdash; _Type_.

[,julia]
----
DenseVecOrMat{T}
----

Union type of xref:arrays.adoc#Base.DenseVector[`+DenseVector{T}+`] and xref:arrays.adoc#Base.DenseMatrix[`+DenseMatrix{T}+`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L114-L118[source] +

[id="Base.StridedArray"]
==== *`Base.StridedArray`* &mdash; _Type_.

[,julia]
----
StridedArray{T, N}
----

A hard-coded xref:base.adoc#Core.Union[`Union`] of common array types that follow the xref:../manual/interfaces.adoc#man-interface-strided-arrays[strided array interface], with elements of type `T` and `N` dimensions.

If `A` is a `StridedArray`, then its elements are stored in memory with offsets, which may vary between dimensions but are constant within a dimension. For example, `A` could have stride 2 in dimension 1, and stride 3 in dimension 2. Incrementing `A` along dimension `d` jumps in memory by [`strides(A, d)`] slots. Strided arrays are particularly important and useful because they can sometimes be passed directly as pointers to foreign language libraries like BLAS.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2776-L2788[source] +

[id="Base.StridedVector"]
==== *`Base.StridedVector`* &mdash; _Type_.

[,julia]
----
StridedVector{T}
----

One dimensional xref:arrays.adoc#Base.StridedArray[`StridedArray`] with elements of type `T`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2791-L2795[source] +

[id="Base.StridedMatrix"]
==== *`Base.StridedMatrix`* &mdash; _Type_.

[,julia]
----
StridedMatrix{T}
----

Two dimensional xref:arrays.adoc#Base.StridedArray[`StridedArray`] with elements of type `T`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2798-L2802[source] +

[id="Base.StridedVecOrMat"]
==== *`Base.StridedVecOrMat`* &mdash; _Type_.

[,julia]
----
StridedVecOrMat{T}
----

Union type of xref:arrays.adoc#Base.StridedVector[`StridedVector`] and xref:arrays.adoc#Base.StridedMatrix[`StridedMatrix`] with elements of type `T`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/docs/basedocs.jl#L2805-L2809[source] +

[id="Base.getindex-Tuple{Type, Vararg{Any}}"]
==== *`Base.getindex`* &mdash; _Method_.

[,julia]
----
getindex(type[, elements...])
----

Construct a 1-d array of the specified type. This is usually called with the syntax `Type[]`. Element values can be specified using `+Type[a,b,c,...]+`.

*Examples*

[,julia-repl]
----
julia> Int8[1, 2, 3]
3-element Vector{Int8}:
 1
 2
 3

julia> getindex(Int8, 1, 2, 3)
3-element Vector{Int8}:
 1
 2
 3
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L382-L402[source] +

[id="Base.zeros"]
==== *`Base.zeros`* &mdash; _Function_.

[,julia]
----
zeros([T=Float64,] dims::Tuple)
zeros([T=Float64,] dims...)
----

Create an `Array`, with element type `T`, of all zeros with size specified by `dims`. See also xref:arrays.adoc#Base.fill[`fill`], xref:arrays.adoc#Base.ones[`ones`], xref:numbers.adoc#Base.zero[`zero`].

*Examples*

[,julia-repl]
----
julia> zeros(1)
1-element Vector{Float64}:
 0.0

julia> zeros(Int8, 2, 3)
2×3 Matrix{Int8}:
 0  0  0
 0  0  0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L539-L557[source] +

[id="Base.ones"]
==== *`Base.ones`* &mdash; _Function_.

[,julia]
----
ones([T=Float64,] dims::Tuple)
ones([T=Float64,] dims...)
----

Create an `Array`, with element type `T`, of all ones with size specified by `dims`. See also xref:arrays.adoc#Base.fill[`fill`], xref:arrays.adoc#Base.zeros[`zeros`].

*Examples*

[,julia-repl]
----
julia> ones(1,2)
1×2 Matrix{Float64}:
 1.0  1.0

julia> ones(ComplexF64, 2, 3)
2×3 Matrix{ComplexF64}:
 1.0+0.0im  1.0+0.0im  1.0+0.0im
 1.0+0.0im  1.0+0.0im  1.0+0.0im
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L560-L578[source] +

[id="Base.BitArray"]
==== *`Base.BitArray`* &mdash; _Type_.

[,julia]
----
BitArray{N} <: AbstractArray{Bool, N}
----

Space-efficient `N`-dimensional boolean array, using just one bit for each boolean value.

``BitArray``s pack up to 64 values into every 8 bytes, resulting in an 8x space efficiency over `Array{Bool, N}` and allowing some operations to work on 64 values at once.

By default, Julia returns `BitArrays` from xref:../manual/arrays.adoc#Broadcasting[broadcasting] operations that generate boolean elements (including dotted-comparisons like `.==`) as well as from the functions xref:arrays.adoc#Base.trues[`trues`] and xref:arrays.adoc#Base.falses[`falses`].

!!! note
    Due to its packed storage format, concurrent access to the elements of a `BitArray` where at least one of them is a write is not thread safe.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/bitarray.jl#L7-L23[source] +

[id="Base.BitArray-Tuple{UndefInitializer, Vararg{Integer}}"]
==== *`Base.BitArray`* &mdash; _Method_.

[,julia]
----
BitArray(undef, dims::Integer...)
BitArray{N}(undef, dims::NTuple{N,Int})
----

Construct an undef xref:arrays.adoc#Base.BitArray[`BitArray`] with the given dimensions. Behaves identically to the xref:arrays.adoc#Core.Array[`Array`] constructor. See xref:arrays.adoc#Core.undef[`undef`].

*Examples*

[,julia-repl]
----
julia> BitArray(undef, 2, 2)
2×2 BitMatrix:
 0  0
 0  0

julia> BitArray(undef, (3, 1))
3×1 BitMatrix:
 0
 0
 0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/bitarray.jl#L48-L68[source] +

[id="Base.BitArray-Tuple{Any}"]
==== *`Base.BitArray`* &mdash; _Method_.

[,julia]
----
BitArray(itr)
----

Construct a xref:arrays.adoc#Base.BitArray[`BitArray`] generated by the given iterable object. The shape is inferred from the `itr` object.

*Examples*

[,julia-repl]
----
julia> BitArray([1 0; 0 1])
2×2 BitMatrix:
 1  0
 0  1

julia> BitArray(x+y == 3 for x = 1:2, y = 1:3)
2×3 BitMatrix:
 0  1  0
 1  0  0

julia> BitArray(x+y == 3 for x = 1:2 for y = 1:3)
6-element BitVector:
 0
 1
 0
 1
 0
 0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/bitarray.jl#L549-L576[source] +

[id="Base.trues"]
==== *`Base.trues`* &mdash; _Function_.

[,julia]
----
trues(dims)
----

Create a `BitArray` with all values set to `true`.

*Examples*

[,julia-repl]
----
julia> trues(2,3)
2×3 BitMatrix:
 1  1  1
 1  1  1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/bitarray.jl#L408-L420[source] +

[id="Base.falses"]
==== *`Base.falses`* &mdash; _Function_.

[,julia]
----
falses(dims)
----

Create a `BitArray` with all values set to `false`.

*Examples*

[,julia-repl]
----
julia> falses(2,3)
2×3 BitMatrix:
 0  0  0
 0  0  0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/bitarray.jl#L390-L402[source] +

[id="Base.fill"]
==== *`Base.fill`* &mdash; _Function_.

[,julia]
----
fill(value, dims::Tuple)
fill(value, dims...)
----

Create an array of size `dims` with every location set to `value`.

For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with `1.0` in every location of the array.

The dimension lengths `dims` may be specified as either a tuple or a sequence of arguments. An `N`-length tuple or `N` arguments following the `value` specify an `N`-dimensional array. Thus, a common idiom for creating a zero-dimensional array with its only location set to `x` is `fill(x)`.

Every location of the returned array is set to (and is thus xref:base.adoc#Core.:===[`===`] to) the `value` that was passed; this means that if the `value` is itself modified, all elements of the ``fill``ed array will reflect that modification because they're _still_ that very `value`. This is of no concern with `fill(1.0, (5,5))` as the `value` `1.0` is immutable and cannot itself be modified, but can be unexpected with mutable values like -- most commonly -- arrays.  For example, `fill([], 3)` places _the very same_ empty array in all three locations of the returned vector:

[,julia-repl]
----
julia> v = fill([], 3)
3-element Vector{Vector{Any}}:
 []
 []
 []

julia> v[1] === v[2] === v[3]
true

julia> value = v[1]
Any[]

julia> push!(value, 867_5309)
1-element Vector{Any}:
 8675309

julia> v
3-element Vector{Vector{Any}}:
 [8675309]
 [8675309]
 [8675309]
----

To create an array of many independent inner arrays, use a xref:../manual/arrays.adoc#man-comprehensions[comprehension] instead. This creates a new and distinct array on each iteration of the loop:

[,julia-repl]
----
julia> v2 = [[] for _ in 1:3]
3-element Vector{Vector{Any}}:
 []
 []
 []

julia> v2[1] === v2[2] === v2[3]
false

julia> push!(v2[1], 8675309)
1-element Vector{Any}:
 8675309

julia> v2
3-element Vector{Vector{Any}}:
 [8675309]
 []
 []
----

See also: xref:arrays.adoc#Base.fill![`fill!`], xref:arrays.adoc#Base.zeros[`zeros`], xref:arrays.adoc#Base.ones[`ones`], xref:arrays.adoc#Base.similar[`similar`].

*Examples*

[,julia-repl]
----
julia> fill(1.0, (2,3))
2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

julia> fill(42)
0-dimensional Array{Int64, 0}:
42

julia> A = fill(zeros(2), 2) # sets both elements to the same [0.0, 0.0] vector
2-element Vector{Vector{Float64}}:
 [0.0, 0.0]
 [0.0, 0.0]

julia> A[1][1] = 42; # modifies the filled value to be [42.0, 0.0]

julia> A # both A[1] and A[2] are the very same vector
2-element Vector{Vector{Float64}}:
 [42.0, 0.0]
 [42.0, 0.0]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L436-L531[source] +

[id="Base.fill!"]
==== *`Base.fill!`* &mdash; _Function_.

[,julia]
----
fill!(A, x)
----

Fill array `A` with the value `x`. If `x` is an object reference, all elements will refer to the same object. `fill!(A, Foo())` will return `A` filled with the result of evaluating `Foo()` once.

*Examples*

[,julia-repl]
----
julia> A = zeros(2,3)
2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> fill!(A, 2.)
2×3 Matrix{Float64}:
 2.0  2.0  2.0
 2.0  2.0  2.0

julia> a = [1, 1, 1]; A = fill!(Vector{Vector{Int}}(undef, 3), a); a[1] = 2; A
3-element Vector{Vector{Int64}}:
 [2, 1, 1]
 [2, 1, 1]
 [2, 1, 1]

julia> x = 0; f() = (global x += 1; x); fill!(Vector{Int}(undef, 3), f())
3-element Vector{Int64}:
 1
 1
 1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/multidimensional.jl#L1065-L1096[source] +

[id="Base.empty"]
==== *`Base.empty`* &mdash; _Function_.

[,julia]
----
empty(x::Tuple)
----

Returns an empty tuple, `()`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/tuple.jl#L548-L552[source] +

----
empty(v::AbstractVector, [eltype])
----

Create an empty vector similar to `v`, optionally changing the `eltype`.

See also: xref:collections.adoc#Base.empty![`empty!`], xref:collections.adoc#Base.isempty[`isempty`], xref:arrays.adoc#Base.isassigned[`isassigned`].

*Examples*

[,julia-repl]
----
julia> empty([1.0, 2.0, 3.0])
Float64[]

julia> empty([1.0, 2.0, 3.0], String)
String[]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L843-L859[source] +

----
empty(a::AbstractDict, [index_type=keytype(a)], [value_type=valtype(a)])
----

Create an empty `AbstractDict` container which can accept indices of type `index_type` and values of type `value_type`. The second and third arguments are optional and default to the input's `keytype` and `valtype`, respectively. (If only one of the two types is specified, it is assumed to be the `value_type`, and the `index_type` we default to `keytype(a)`).

Custom `AbstractDict` subtypes may choose which specific dictionary type is best suited to return for the given index and value types, by specializing on the three-argument signature. The default is to return an empty `Dict`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractdict.jl#L176-L187[source] +

[id="Base.similar"]
==== *`Base.similar`* &mdash; _Function_.

[,julia]
----
similar(array, [element_type=eltype(array)], [dims=size(array)])
----

Create an uninitialized mutable array with the given element type and size, based upon the given source array. The second and third arguments are both optional, defaulting to the given array's `eltype` and `size`. The dimensions may be specified either as a single tuple argument or as a series of integer arguments.

Custom AbstractArray subtypes may choose which specific array type is best-suited to return for the given element type and dimensionality. If they do not specialize this method, the default is an `+Array{element_type}(undef, dims...)+`.

For example, `similar(1:10, 1, 4)` returns an uninitialized `Array{Int,2}` since ranges are neither mutable nor support 2 dimensions:

[,julia-repl]
----
julia> similar(1:10, 1, 4)
1×4 Matrix{Int64}:
 4419743872  4374413872  4419743888  0
----

Conversely, `similar(trues(10,10), 2)` returns an uninitialized `BitVector` with two elements since ``BitArray``s are both mutable and can support 1-dimensional arrays:

[,julia-repl]
----
julia> similar(trues(10,10), 2)
2-element BitVector:
 0
 0
----

Since ``BitArray``s can only store elements of type xref:numbers.adoc#Core.Bool[`Bool`], however, if you request a different element type it will create a regular `Array` instead:

[,julia-repl]
----
julia> similar(falses(10), Float64, 2, 4)
2×4 Matrix{Float64}:
 2.18425e-314  2.18425e-314  2.18425e-314  2.18425e-314
 2.18425e-314  2.18425e-314  2.18425e-314  2.18425e-314
----

See also: xref:arrays.adoc#Core.undef[`undef`], xref:arrays.adoc#Base.isassigned[`isassigned`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L750-L792[source] +

----
similar(storagetype, axes)
----

Create an uninitialized mutable array analogous to that specified by `storagetype`, but with `axes` specified by the last argument.

*Examples*:

----
similar(Array{Int}, axes(A))
----

creates an array that "acts like" an `+Array{Int}+` (and might indeed be backed by one), but which is indexed identically to `A`. If `A` has conventional indexing, this will be identical to `+Array{Int}(undef, size(A))+`, but if `A` has unconventional indexing then the indices of the result will match `A`.

----
similar(BitArray, (axes(A, 2),))
----

would create a 1-dimensional logical array whose indices match those of the columns of `A`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L817-L838[source] +

+++<a id="Basic-functions">++++++</a>+++

+++<a id="Basic-functions-1">++++++</a>+++

== Basic functions

[id="Base.ndims"]
==== *`Base.ndims`* &mdash; _Function_.

[,julia]
----
ndims(A::AbstractArray) -> Integer
----

Тестовый русский текст.

Return the number of dimensions of `A`.

See also: xref:arrays.adoc#Base.size[`size`], xref:arrays.adoc#Base.axes-Tuple{Any}[`axes`].

*Examples*

[,julia-repl]
----
julia> A = fill(1, (3,4,5));

julia> ndims(A)
3
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L224-L240[source] +

[id="Base.size"]
==== *`Base.size`* &mdash; _Function_.

[,julia]
----
size(A::AbstractArray, [dim])
----

Return a tuple containing the dimensions of `A`. Optionally you can specify a dimension to just get the length of that dimension.

Note that `size` may not be defined for arrays with non-standard indices, in which case xref:arrays.adoc#Base.axes-Tuple{Any}[`axes`] may be useful. See the manual chapter on xref:../devdocs/offset-arrays.adoc#man-custom-indices[arrays with custom indices].

See also: xref:collections.adoc#Base.length[`length`], xref:arrays.adoc#Base.ndims[`ndims`], xref:arrays.adoc#Base.eachindex[`eachindex`], xref:base.adoc#Base.sizeof-Tuple{Type}[`sizeof`].

*Examples*

[,julia-repl]
----
julia> A = fill(1, (2,3,4));

julia> size(A)
(2, 3, 4)

julia> size(A, 2)
3
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L20-L41[source] +

[id="Base.axes-Tuple{Any}"]
==== *`Base.axes`* &mdash; _Method_.

[,julia]
----
axes(A)
----

Return the tuple of valid indices for array `A`.

See also: xref:arrays.adoc#Base.size[`size`], xref:collections.adoc#Base.keys[`keys`], xref:arrays.adoc#Base.eachindex[`eachindex`].

*Examples*

[,julia-repl]
----
julia> A = fill(1, (5,6,7));

julia> axes(A)
(Base.OneTo(5), Base.OneTo(6), Base.OneTo(7))
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L77-L92[source] +

[id="Base.axes-Tuple{AbstractArray, Any}"]
==== *`Base.axes`* &mdash; _Method_.

[,julia]
----
axes(A, d)
----

Тестовый русский текст.

Return the valid range of indices for array `A` along dimension `d`.

See also xref:arrays.adoc#Base.size[`size`], and the manual chapter on xref:../devdocs/offset-arrays.adoc#man-custom-indices[arrays with custom indices].

*Examples*

[,julia-repl]
----
julia> A = fill(1, (5,6,7));

julia> axes(A, 2)
Base.OneTo(6)
----

*Usage note*

Each of the indices has to be an `AbstractUnitRange{<:Integer}`, but at the same time can be a type that uses custom indices. So, for example, if you need a subset, use generalized indexing constructs like `begin`/`end` or xref:collections.adoc#Base.firstindex[`firstindex`]/xref:collections.adoc#Base.lastindex[`lastindex`]:

[,julia]
----
ix = axes(v, 1)
ix[2:end]          # will work for eg Vector, but may fail in general
ix[(begin+1):end]  # works for generalized indexes
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L44-L73[source] +

[id="Base.length-Tuple{AbstractArray}"]
==== *`Base.length`* &mdash; _Method_.

[,julia]
----
length(A::AbstractArray)
----

Return the number of elements in the array, defaults to `prod(size(A))`.

*Examples*

[,julia-repl]
----
julia> length([1, 2, 3, 4])
4

julia> length([1 2; 3 4])
4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L265-L278[source] +

[id="Base.keys-Tuple{AbstractArray}"]
==== *`Base.keys`* &mdash; _Method_.

[,julia]
----
keys(a::AbstractArray)
----

Return an efficient array describing all valid indices for `a` arranged in the shape of `a` itself.

They keys of 1-dimensional arrays (vectors) are integers, whereas all other N-dimensional arrays use xref:arrays.adoc#Base.IteratorsMD.CartesianIndex[`CartesianIndex`] to describe their locations.  Often the special array types xref:arrays.adoc#Base.LinearIndices[`LinearIndices`] and xref:arrays.adoc#Base.IteratorsMD.CartesianIndices[`CartesianIndices`] are used to efficiently represent these arrays of integers and ``CartesianIndex``es, respectively.

Note that the `keys` of an array might not be the most efficient index type; for maximum performance use  xref:arrays.adoc#Base.eachindex[`eachindex`] instead.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L119-L131[source] +

[id="Base.eachindex"]
==== *`Base.eachindex`* &mdash; _Function_.

[,julia]
----
eachindex(A...)
----

Create an iterable object for visiting each index of an `AbstractArray` `A` in an efficient manner. For array types that have opted into fast linear indexing (like `Array`), this is simply the range `1:length(A)`. For other array types, return a specialized Cartesian range to efficiently index into the array with indices specified for every dimension. For other iterables, including strings and dictionaries, return an iterator object supporting arbitrary index types (e.g. unevenly spaced or non-integer indices).

If you supply more than one `AbstractArray` argument, `eachindex` will create an iterable object that is fast for all arguments (a xref:collections.adoc#Base.UnitRange[`UnitRange`] if all inputs have fast linear indexing, a xref:arrays.adoc#Base.IteratorsMD.CartesianIndices[`CartesianIndices`] otherwise). If the arrays have different sizes and/or dimensionalities, a `DimensionMismatch` exception will be thrown.

*Examples*

[,julia-repl]
----
julia> A = [1 2; 3 4];

julia> for i in eachindex(A) # linear indexing
           println(i)
       end
1
2
3
4

julia> for i in eachindex(view(A, 1:2, 1:1)) # Cartesian indexing
           println(i)
       end
CartesianIndex(1, 1)
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L295-L329[source] +

[id="Base.IndexStyle"]
==== *`Base.IndexStyle`* &mdash; _Type_.

[,julia]
----
IndexStyle(A)
IndexStyle(typeof(A))
----

`IndexStyle` specifies the "native indexing style" for array `A`. When you define a new xref:arrays.adoc#Core.AbstractArray[`AbstractArray`] type, you can choose to implement either linear indexing (with xref:arrays.adoc#Base.IndexLinear[`IndexLinear`]) or cartesian indexing. If you decide to only implement linear indexing, then you must set this trait for your array type:

----
Base.IndexStyle(::Type{<:MyArray}) = IndexLinear()
----

The default is xref:arrays.adoc#Base.IndexCartesian[`IndexCartesian()`].

Julia's internal indexing machinery will automatically (and invisibly) recompute all indexing operations into the preferred style. This allows users to access elements of your array using any indexing style, even when explicit methods have not been provided.

If you define both styles of indexing for your `AbstractArray`, this trait can be used to select the most performant indexing style. Some methods check this trait on their inputs, and dispatch to different algorithms depending on the most efficient access pattern. In particular, xref:arrays.adoc#Base.eachindex[`eachindex`] creates an iterator whose type depends on the setting of this trait.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/indices.jl#L68-L93[source] +

[id="Base.IndexLinear"]
==== *`Base.IndexLinear`* &mdash; _Type_.

[,julia]
----
IndexLinear()
----

Subtype of xref:arrays.adoc#Base.IndexStyle[`IndexStyle`] used to describe arrays which are optimally indexed by one linear index.

A linear indexing style uses one integer index to describe the position in the array (even if it's a multidimensional array) and column-major ordering is used to efficiently access the elements. This means that requesting xref:arrays.adoc#Base.eachindex[`eachindex`] from an array that is `IndexLinear` will return a simple one-dimensional range, even if it is multidimensional.

A custom array that reports its `IndexStyle` as `IndexLinear` only needs to implement indexing (and indexed assignment) with a single `Int` index; all other indexing expressions -- including multidimensional accesses -- will be recomputed to the linear index.  For example, if `A` were a `2×3` custom matrix with linear indexing, and we referenced `A[1, 3]`, this would be recomputed to the equivalent linear index and call `A[5]` since `2*1 + 3 = 5`.

See also xref:arrays.adoc#Base.IndexCartesian[`IndexCartesian`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/indices.jl#L16-L36[source] +

[id="Base.IndexCartesian"]
==== *`Base.IndexCartesian`* &mdash; _Type_.

[,julia]
----
IndexCartesian()
----

Subtype of xref:arrays.adoc#Base.IndexStyle[`IndexStyle`] used to describe arrays which are optimally indexed by a Cartesian index. This is the default for new custom xref:arrays.adoc#Core.AbstractArray[`AbstractArray`] subtypes.

A Cartesian indexing style uses multiple integer indices to describe the position in a multidimensional array, with exactly one index per dimension. This means that requesting xref:arrays.adoc#Base.eachindex[`eachindex`] from an array that is `IndexCartesian` will return a range of xref:arrays.adoc#Base.IteratorsMD.CartesianIndices[`CartesianIndices`].

A `N`-dimensional custom array that reports its `IndexStyle` as `IndexCartesian` needs to implement indexing (and indexed assignment) with exactly `N` `Int` indices; all other indexing expressions -- including linear indexing -- will be recomputed to the equivalent Cartesian location.  For example, if `A` were a `2×3` custom matrix with cartesian indexing, and we referenced `A[5]`, this would be recomputed to the equivalent Cartesian index and call `A[1, 3]` since `5 = 2*1 + 3`.

It is significantly more expensive to compute Cartesian indices from a linear index than it is to go the other way.  The former operation requires division -- a very costly operation -- whereas the latter only uses multiplication and addition and is essentially free. This asymmetry means it is far more costly to use linear indexing with an `IndexCartesian` array than it is to use Cartesian indexing with an `IndexLinear` array.

See also xref:arrays.adoc#Base.IndexLinear[`IndexLinear`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/indices.jl#L39-L65[source] +

[id="Base.conj!"]
==== *`Base.conj!`* &mdash; _Function_.

[,julia]
----
conj!(A)
----

Transform an array to its complex conjugate in-place.

See also xref:math.adoc#Base.conj[`conj`].

*Examples*

[,julia-repl]
----
julia> A = [1+im 2-im; 2+2im 3+im]
2×2 Matrix{Complex{Int64}}:
 1+1im  2-1im
 2+2im  3+1im

julia> conj!(A);

julia> A
2×2 Matrix{Complex{Int64}}:
 1-1im  2+1im
 2-2im  3-1im
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L98-L119[source] +

[id="Base.stride"]
==== *`Base.stride`* &mdash; _Function_.

[,julia]
----
stride(A, k::Integer)
----

Return the distance in memory (in number of elements) between adjacent elements in dimension `k`.

See also: xref:arrays.adoc#Base.strides[`strides`].

*Examples*

[,julia-repl]
----
julia> A = fill(1, (3,4,5));

julia> stride(A,2)
3

julia> stride(A,3)
12
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L528-L545[source] +

[id="Base.strides"]
==== *`Base.strides`* &mdash; _Function_.

[,julia]
----
strides(A)
----

Return a tuple of the memory strides in each dimension.

See also: xref:arrays.adoc#Base.stride[`stride`].

*Examples*

[,julia-repl]
----
julia> A = fill(1, (3,4,5));

julia> strides(A)
(1, 3, 12)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L511-L525[source] +

+++<a id="Broadcast-and-vectorization">++++++</a>+++

+++<a id="Broadcast-and-vectorization-1">++++++</a>+++

== Broadcast and vectorization

See also the xref:../manual/functions.adoc#man-vectorized[dot syntax for vectorizing functions]; for example, `+f.(args...)+` implicitly calls `+broadcast(f, args...)+`. Rather than relying on "vectorized" methods of functions like `sin` to operate on arrays, you should use `sin.(a)` to vectorize via `broadcast`.

[id="Base.Broadcast.broadcast"]
==== *`Base.Broadcast.broadcast`* &mdash; _Function_.

[,julia]
----
broadcast(f, As...)
----

Broadcast the function `f` over the arrays, tuples, collections, xref:c.adoc#Core.Ref[`Ref`]s and/or scalars `As`.

Broadcasting applies the function `f` over the elements of the container arguments and the scalars themselves in `As`. Singleton and missing dimensions are expanded to match the extents of the other arguments by virtually repeating the value. By default, only a limited number of types are considered scalars, including ``Number``s, ``String``s, ``Symbol``s, ``Type``s, ``Function``s and some common singletons like xref:base.adoc#Base.missing[`missing`] and xref:constants.adoc#Core.nothing[`nothing`]. All other arguments are iterated over or indexed into elementwise.

The resulting container type is established by the following rules:

* If all the arguments are scalars or zero-dimensional arrays, it returns an unwrapped scalar.
* If at least one argument is a tuple and all others are scalars or zero-dimensional arrays, it returns a tuple.
* All other combinations of arguments default to returning an `Array`, but custom container types can define their own implementation and promotion-like rules to customize the result when they appear as arguments.

A special syntax exists for broadcasting: `+f.(args...)+` is equivalent to `+broadcast(f, args...)+`, and nested `+f.(g.(args...))+` calls are fused into a single broadcast loop.

*Examples*

[,julia-repl]
----
julia> A = [1, 2, 3, 4, 5]
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> B = [1 2; 3 4; 5 6; 7 8; 9 10]
5×2 Matrix{Int64}:
 1   2
 3   4
 5   6
 7   8
 9  10

julia> broadcast(+, A, B)
5×2 Matrix{Int64}:
  2   3
  5   6
  8   9
 11  12
 14  15

julia> parse.(Int, ["1", "2"])
2-element Vector{Int64}:
 1
 2

julia> abs.((1, -2))
(1, 2)

julia> broadcast(+, 1.0, (0, -2.0))
(1.0, -1.0)

julia> (+).([[0,2], [1,3]], Ref{Vector{Int}}([1,-1]))
2-element Vector{Vector{Int64}}:
 [1, 1]
 [2, 2]

julia> string.(("one","two","three","four"), ": ", 1:4)
4-element Vector{String}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L722-L797[source] +

[id="Base.Broadcast.broadcast!"]
==== *`Base.Broadcast.broadcast!`* &mdash; _Function_.

[,julia]
----
broadcast!(f, dest, As...)
----

Like xref:arrays.adoc#Base.Broadcast.broadcast[`broadcast`], but store the result of `+broadcast(f, As...)+` in the `dest` array. Note that `dest` is only used to store the result, and does not supply arguments to `f` unless it is also listed in the `As`, as in `broadcast!(f, A, A, B)` to perform `A[:] = broadcast(f, A, B)`.

*Examples*

[,julia-repl]
----
julia> A = [1.0; 0.0]; B = [0.0; 0.0];

julia> broadcast!(+, B, A, (0, -2.0));

julia> B
2-element Vector{Float64}:
  1.0
 -2.0

julia> A
2-element Vector{Float64}:
 1.0
 0.0

julia> broadcast!(+, A, A, (0, -2.0));

julia> A
2-element Vector{Float64}:
  1.0
 -2.0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L804-L836[source] +

[id="Base.Broadcast.@__dot__"]
==== *`Base.Broadcast.@__dot__`* &mdash; _Macro_.

[,julia]
----
@. expr
----

Convert every function call or operator in `expr` into a "dot call" (e.g. convert `f(x)` to `f.(x)`), and convert every assignment in `expr` to a "dot assignment" (e.g. convert `+=` to `.+=`).

If you want to _avoid_ adding dots for selected function calls in `expr`, splice those function calls in with `$`.  For example, `@. sqrt(abs($sort(x)))` is equivalent to `sqrt.(abs.(sort(x)))` (no dot for `sort`).

(`@.` is equivalent to a call to `@__dot__`.)

*Examples*

[,julia-repl]
----
julia> x = 1.0:3.0; y = similar(x);

julia> @. y = x + 3 * sin(x)
3-element Vector{Float64}:
 3.5244129544236893
 4.727892280477045
 3.4233600241796016
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L1251-L1275[source] +

For specializing broadcast on custom types, see

[id="Base.Broadcast.BroadcastStyle"]
==== *`Base.Broadcast.BroadcastStyle`* &mdash; _Type_.

`BroadcastStyle` is an abstract type and trait-function used to determine behavior of objects under broadcasting. `BroadcastStyle(typeof(x))` returns the style associated with `x`. To customize the broadcasting behavior of a type, one can declare a style by defining a type/method pair

----
struct MyContainerStyle <: BroadcastStyle end
Base.BroadcastStyle(::Type{<:MyContainer}) = MyContainerStyle()
----

One then writes method(s) (at least xref:arrays.adoc#Base.similar[`similar`]) operating on `+Broadcasted{MyContainerStyle}+`. There are also several pre-defined subtypes of `BroadcastStyle` that you may be able to leverage; see the xref:../manual/interfaces.adoc#man-interfaces-broadcasting[Interfaces chapter] for more information.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L21-L34[source] +

[id="Base.Broadcast.AbstractArrayStyle"]
==== *`Base.Broadcast.AbstractArrayStyle`* &mdash; _Type_.

`+Broadcast.AbstractArrayStyle{N} <: BroadcastStyle+` is the abstract supertype for any style associated with an `AbstractArray` type. The `N` parameter is the dimensionality, which can be handy for AbstractArray types that only support specific dimensionalities:

----
struct SparseMatrixStyle <: Broadcast.AbstractArrayStyle{2} end
Base.BroadcastStyle(::Type{<:SparseMatrixCSC}) = SparseMatrixStyle()
----

For `AbstractArray` types that support arbitrary dimensionality, `N` can be set to `Any`:

----
struct MyArrayStyle <: Broadcast.AbstractArrayStyle{Any} end
Base.BroadcastStyle(::Type{<:MyArray}) = MyArrayStyle()
----

In cases where you want to be able to mix multiple ``AbstractArrayStyle``s and keep track of dimensionality, your style needs to support a xref:base.adoc#Base.Val[`Val`] constructor:

----
struct MyArrayStyleDim{N} <: Broadcast.AbstractArrayStyle{N} end
(::Type{<:MyArrayStyleDim})(::Val{N}) where N = MyArrayStyleDim{N}()
----

Note that if two or more `AbstractArrayStyle` subtypes conflict, broadcasting machinery will fall back to producing ``Array``s. If this is undesirable, you may need to define binary xref:arrays.adoc#Base.Broadcast.BroadcastStyle[`BroadcastStyle`] rules to control the output type.

See also xref:arrays.adoc#Base.Broadcast.DefaultArrayStyle[`Broadcast.DefaultArrayStyle`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L51-L76[source] +

[id="Base.Broadcast.ArrayStyle"]
==== *`Base.Broadcast.ArrayStyle`* &mdash; _Type_.

`+Broadcast.ArrayStyle{MyArrayType}()+` is a xref:arrays.adoc#Base.Broadcast.BroadcastStyle[`BroadcastStyle`] indicating that an object behaves as an array for broadcasting. It presents a simple way to construct xref:arrays.adoc#Base.Broadcast.AbstractArrayStyle[`Broadcast.AbstractArrayStyle`]s for specific `AbstractArray` container types. Broadcast styles created this way lose track of dimensionality; if keeping track is important for your type, you should create your own custom xref:arrays.adoc#Base.Broadcast.AbstractArrayStyle[`Broadcast.AbstractArrayStyle`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L79-L85[source] +

[id="Base.Broadcast.DefaultArrayStyle"]
==== *`Base.Broadcast.DefaultArrayStyle`* &mdash; _Type_.

`+Broadcast.DefaultArrayStyle{N}()+` is a xref:arrays.adoc#Base.Broadcast.BroadcastStyle[`BroadcastStyle`] indicating that an object behaves as an `N`-dimensional array for broadcasting. Specifically, `DefaultArrayStyle` is used for any `AbstractArray` type that hasn't defined a specialized style, and in the absence of overrides from other `broadcast` arguments the resulting output type is `Array`. When there are multiple inputs to `broadcast`, `DefaultArrayStyle` "loses" to any other xref:arrays.adoc#Base.Broadcast.ArrayStyle[`Broadcast.ArrayStyle`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L89-L96[source] +

[id="Base.Broadcast.broadcastable"]
==== *`Base.Broadcast.broadcastable`* &mdash; _Function_.

[,julia]
----
Broadcast.broadcastable(x)
----

Return either `x` or an object like `x` such that it supports xref:arrays.adoc#Base.axes-Tuple{Any}[`axes`], indexing, and its type supports xref:arrays.adoc#Base.ndims[`ndims`].

If `x` supports iteration, the returned value should have the same `axes` and indexing behaviors as xref:collections.adoc#Base.collect-Tuple{Any}[`collect(x)`].

If `x` is not an `AbstractArray` but it supports `axes`, indexing, and its type supports `ndims`, then `broadcastable(::typeof(x))` may be implemented to just return itself. Further, if `x` defines its own xref:arrays.adoc#Base.Broadcast.BroadcastStyle[`BroadcastStyle`], then it must define its `broadcastable` method to return itself for the custom style to have any effect.

*Examples*

[,julia-repl]
----
julia> Broadcast.broadcastable([1,2,3]) # like `identity` since arrays already support axes and indexing
3-element Vector{Int64}:
 1
 2
 3

julia> Broadcast.broadcastable(Int) # Types don't support axes, indexing, or iteration but are commonly used as scalars
Base.RefValue{Type{Int64}}(Int64)

julia> Broadcast.broadcastable("hello") # Strings break convention of matching iteration and act like a scalar instead
Base.RefValue{String}("hello")
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L672-L699[source] +

[id="Base.Broadcast.combine_axes"]
==== *`Base.Broadcast.combine_axes`* &mdash; _Function_.

[,julia]
----
combine_axes(As...) -> Tuple
----

Determine the result axes for broadcasting across all values in `As`.

[,julia-repl]
----
julia> Broadcast.combine_axes([1], [1 2; 3 4; 5 6])
(Base.OneTo(3), Base.OneTo(2))

julia> Broadcast.combine_axes(1, 1, 1)
()
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L485-L497[source] +

[id="Base.Broadcast.combine_styles"]
==== *`Base.Broadcast.combine_styles`* &mdash; _Function_.

[,julia]
----
combine_styles(cs...) -> BroadcastStyle
----

Decides which `BroadcastStyle` to use for any number of value arguments. Uses xref:arrays.adoc#Base.Broadcast.BroadcastStyle[`BroadcastStyle`] to get the style for each argument, and uses xref:arrays.adoc#Base.Broadcast.result_style[`result_style`] to combine styles.

*Examples*

[,julia-repl]
----
julia> Broadcast.combine_styles([1], [1 2; 3 4])
Base.Broadcast.DefaultArrayStyle{2}()
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L418-L431[source] +

[id="Base.Broadcast.result_style"]
==== *`Base.Broadcast.result_style`* &mdash; _Function_.

[,julia]
----
result_style(s1::BroadcastStyle[, s2::BroadcastStyle]) -> BroadcastStyle
----

Takes one or two ``BroadcastStyle``s and combines them using xref:arrays.adoc#Base.Broadcast.BroadcastStyle[`BroadcastStyle`] to determine a common `BroadcastStyle`.

*Examples*

[,julia-repl]
----
julia> Broadcast.result_style(Broadcast.DefaultArrayStyle{0}(), Broadcast.DefaultArrayStyle{3}())
Base.Broadcast.DefaultArrayStyle{3}()

julia> Broadcast.result_style(Broadcast.Unknown(), Broadcast.DefaultArrayStyle{1}())
Base.Broadcast.DefaultArrayStyle{1}()
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/broadcast.jl#L439-L454[source] +

+++<a id="Indexing-and-assignment">++++++</a>+++

+++<a id="Indexing-and-assignment-1">++++++</a>+++

== Indexing and assignment

[id="Base.getindex-Tuple{AbstractArray, Vararg{Any}}"]
==== *`Base.getindex`* &mdash; _Method_.

[,julia]
----
getindex(A, inds...)
----

Return a subset of array `A` as specified by `inds`, where each `ind` may be, for example, an `Int`, an xref:collections.adoc#Base.AbstractRange[`AbstractRange`], or a xref:arrays.adoc#Base.Vector[`Vector`]. See the manual section on xref:../manual/arrays.adoc#man-array-indexing[array indexing] for details.

*Examples*

[,julia-repl]
----
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> getindex(A, 1)
1

julia> getindex(A, [2, 1])
2-element Vector{Int64}:
 3
 1

julia> getindex(A, 2:4)
3-element Vector{Int64}:
 3
 2
 4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L1209-L1237[source] +

[id="Base.setindex!-Tuple{AbstractArray, Any, Vararg{Any}}"]
==== *`Base.setindex!`* &mdash; _Method_.

[,julia]
----
setindex!(A, X, inds...)
A[inds...] = X
----

Store values from array `X` within some subset of `A` as specified by `inds`. The syntax `+A[inds...] = X+` is equivalent to `+(setindex!(A, X, inds...); X)+`.

*Examples*

[,julia-repl]
----
julia> A = zeros(2,2);

julia> setindex!(A, [10, 20], [1, 2]);

julia> A[[3, 4]] = [30, 40];

julia> A
2×2 Matrix{Float64}:
 10.0  30.0
 20.0  40.0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L1320-L1340[source] +

[id="Base.copyto!-Tuple{AbstractArray, CartesianIndices, AbstractArray, CartesianIndices}"]
==== *`Base.copyto!`* &mdash; _Method_.

[,julia]
----
copyto!(dest, Rdest::CartesianIndices, src, Rsrc::CartesianIndices) -> dest
----

Copy the block of `src` in the range of `Rsrc` to the block of `dest` in the range of `Rdest`. The sizes of the two regions must match.

*Examples*

[,julia-repl]
----
julia> A = zeros(5, 5);

julia> B = [1 2; 3 4];

julia> Ainds = CartesianIndices((2:3, 2:3));

julia> Binds = CartesianIndices(B);

julia> copyto!(A, Ainds, B, Binds)
5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  1.0  2.0  0.0  0.0
 0.0  3.0  4.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/multidimensional.jl#L1133-L1157[source] +

[id="Base.copy!"]
==== *`Base.copy!`* &mdash; _Function_.

[,julia]
----
copy!(dst, src) -> dst
----

In-place xref:base.adoc#Base.copy[`copy`] of `src` into `dst`, discarding any pre-existing elements in `dst`. If `dst` and `src` are of the same type, `dst == src` should hold after the call. If `dst` and `src` are multidimensional arrays, they must have equal xref:arrays.adoc#Base.axes-Tuple{Any}[`axes`].

See also xref:c.adoc#Base.copyto![`copyto!`].

!!! compat "Julia 1.1"
    This method requires at least Julia 1.1. In Julia 1.0 this method is available from the `Future` standard library as `Future.copy!`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L866-L880[source] +

[id="Base.isassigned"]
==== *`Base.isassigned`* &mdash; _Function_.

[,julia]
----
isassigned(array, i) -> Bool
----

Test whether the given array has a value associated with index `i`. Return `false` if the index is out of bounds, or has an undefined reference.

*Examples*

[,julia-repl]
----
julia> isassigned(rand(3, 3), 5)
true

julia> isassigned(rand(3, 3), 3 * 3 + 1)
false

julia> mutable struct Foo end

julia> v = similar(rand(3), Foo)
3-element Vector{Foo}:
 #undef
 #undef
 #undef

julia> isassigned(v, 1)
false
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/essentials.jl#L641-L666[source] +

[id="Base.Colon"]
==== *`Base.Colon`* &mdash; _Type_.

[,julia]
----
Colon()
----

Colons (:) are used to signify indexing entire objects or dimensions at once.

Very few operations are defined on Colons directly; instead they are converted by xref:arrays.adoc#Base.to_indices[`to_indices`] to an internal vector type (`Base.Slice`) to represent the collection of indices they span before being used.

The singleton instance of `Colon` is also a function used to construct ranges; see xref:math.adoc#Base.::[`:`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/essentials.jl#L675-L686[source] +

[id="Base.IteratorsMD.CartesianIndex"]
==== *`Base.IteratorsMD.CartesianIndex`* &mdash; _Type_.

[,julia]
----
CartesianIndex(i, j, k...)   -> I
CartesianIndex((i, j, k...)) -> I
----

Create a multidimensional index `I`, which can be used for indexing a multidimensional array `A`.  In particular, `A[I]` is equivalent to `+A[i,j,k...]+`.  One can freely mix integer and `CartesianIndex` indices; for example, `A[Ipre, i, Ipost]` (where `Ipre` and `Ipost` are `CartesianIndex` indices and `i` is an `Int`) can be a useful expression when writing algorithms that work along a single dimension of an array of arbitrary dimensionality.

A `CartesianIndex` is sometimes produced by xref:arrays.adoc#Base.eachindex[`eachindex`], and always when iterating with an explicit xref:arrays.adoc#Base.IteratorsMD.CartesianIndices[`CartesianIndices`].

*Examples*

[,julia-repl]
----
julia> A = reshape(Vector(1:16), (2, 2, 2, 2))
2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

julia> A[CartesianIndex((1, 1, 1, 1))]
1

julia> A[CartesianIndex((1, 1, 1, 2))]
9

julia> A[CartesianIndex((1, 1, 2, 1))]
5
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/multidimensional.jl#L18-L63[source] +

[id="Base.IteratorsMD.CartesianIndices"]
==== *`Base.IteratorsMD.CartesianIndices`* &mdash; _Type_.

[,julia]
----
CartesianIndices(sz::Dims) -> R
CartesianIndices((istart:[istep:]istop, jstart:[jstep:]jstop, ...)) -> R
----

Define a region `R` spanning a multidimensional rectangular range of integer indices. These are most commonly encountered in the context of iteration, where `+for I in R ... end+` will return xref:arrays.adoc#Base.IteratorsMD.CartesianIndex[`CartesianIndex`] indices `I` equivalent to the nested loops

----
for j = jstart:jstep:jstop
    for i = istart:istep:istop
        ...
    end
end
----

Consequently these can be useful for writing algorithms that work in arbitrary dimensions.

----
CartesianIndices(A::AbstractArray) -> R
----

As a convenience, constructing a `CartesianIndices` from an array makes a range of its indices.

!!! compat "Julia 1.6"
    The step range method `+CartesianIndices((istart:istep:istop, jstart:[jstep:]jstop, ...))+` requires at least Julia 1.6.

*Examples*

[,julia-repl]
----
julia> foreach(println, CartesianIndices((2, 2, 2)))
CartesianIndex(1, 1, 1)
CartesianIndex(2, 1, 1)
CartesianIndex(1, 2, 1)
CartesianIndex(2, 2, 1)
CartesianIndex(1, 1, 2)
CartesianIndex(2, 1, 2)
CartesianIndex(1, 2, 2)
CartesianIndex(2, 2, 2)

julia> CartesianIndices(fill(1, (2,3)))
CartesianIndices((2, 3))
----

*Conversion between linear and cartesian indices*

Linear index to cartesian index conversion exploits the fact that a `CartesianIndices` is an `AbstractArray` and can be indexed linearly:

[,julia-repl]
----
julia> cartesian = CartesianIndices((1:3, 1:2))
CartesianIndices((1:3, 1:2))

julia> cartesian[4]
CartesianIndex(1, 2)

julia> cartesian = CartesianIndices((1:2:5, 1:2))
CartesianIndices((1:2:5, 1:2))

julia> cartesian[2, 2]
CartesianIndex(3, 2)
----

*Broadcasting*

`CartesianIndices` support broadcasting arithmetic (+ and -) with a `CartesianIndex`.

!!! compat "Julia 1.1"
    Broadcasting of CartesianIndices requires at least Julia 1.1.

[,julia-repl]
----
julia> CIs = CartesianIndices((2:3, 5:6))
CartesianIndices((2:3, 5:6))

julia> CI = CartesianIndex(3, 4)
CartesianIndex(3, 4)

julia> CIs .+ CI
CartesianIndices((5:6, 9:10))
----

For cartesian to linear index conversion, see xref:arrays.adoc#Base.LinearIndices[`LinearIndices`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/multidimensional.jl#L166-L247[source] +

[id="Base.Dims"]
==== *`Base.Dims`* &mdash; _Type_.

[,julia]
----
Dims{N}
----

An `NTuple` of `N` ``Int``s used to represent the dimensions of an xref:arrays.adoc#Core.AbstractArray[`AbstractArray`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/indices.jl#L3-L8[source] +

[id="Base.LinearIndices"]
==== *`Base.LinearIndices`* &mdash; _Type_.

[,julia]
----
LinearIndices(A::AbstractArray)
----

Return a `LinearIndices` array with the same shape and xref:arrays.adoc#Base.axes-Tuple{Any}[`axes`] as `A`, holding the linear index of each entry in `A`. Indexing this array with cartesian indices allows mapping them to linear indices.

For arrays with conventional indexing (indices start at 1), or any multidimensional array, linear indices range from 1 to `length(A)`. However, for ``AbstractVector``s linear indices are `axes(A, 1)`, and therefore do not start at 1 for vectors with unconventional indexing.

Calling this function is the "safe" way to write algorithms that exploit linear indexing.

*Examples*

[,julia-repl]
----
julia> A = fill(1, (5,6,7));

julia> b = LinearIndices(A);

julia> extrema(b)
(1, 210)
----

----
LinearIndices(inds::CartesianIndices) -> R
LinearIndices(sz::Dims) -> R
LinearIndices((istart:istop, jstart:jstop, ...)) -> R
----

Return a `LinearIndices` array with the specified shape or xref:arrays.adoc#Base.axes-Tuple{Any}[`axes`].

*Example*

The main purpose of this constructor is intuitive conversion from cartesian to linear indexing:

[,julia-repl]
----
julia> linear = LinearIndices((1:3, 1:2))
3×2 LinearIndices{2, Tuple{UnitRange{Int64}, UnitRange{Int64}}}:
 1  4
 2  5
 3  6

julia> linear[1,2]
4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/indices.jl#L401-L447[source] +

[id="Base.to_indices"]
==== *`Base.to_indices`* &mdash; _Function_.

[,julia]
----
to_indices(A, I::Tuple)
----

Convert the tuple `I` to a tuple of indices for use in indexing into array `A`.

The returned tuple must only contain either ``Int``s or ``AbstractArray``s of scalar indices that are supported by array `A`. It will error upon encountering a novel index type that it does not know how to process.

For simple index types, it defers to the unexported `Base.to_index(A, i)` to process each index `i`. While this internal function is not intended to be called directly, `Base.to_index` may be extended by custom array or index types to provide custom indexing behaviors.

More complicated index types may require more context about the dimension into which they index. To support those cases, `to_indices(A, I)` calls `to_indices(A, axes(A), I)`, which then recursively walks through both the given tuple of indices and the dimensional indices of `A` in tandem. As such, not all index types are guaranteed to propagate to `Base.to_index`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/indices.jl#L304-L323[source] +

[id="Base.checkbounds"]
==== *`Base.checkbounds`* &mdash; _Function_.

[,julia]
----
checkbounds(Bool, A, I...)
----

Return `true` if the specified indices `I` are in bounds for the given array `A`. Subtypes of `AbstractArray` should specialize this method if they need to provide custom bounds checking behaviors; however, in many cases one can rely on ``A``'s indices and xref:arrays.adoc#Base.checkindex[`checkindex`].

See also xref:arrays.adoc#Base.checkindex[`checkindex`].

*Examples*

[,julia-repl]
----
julia> A = rand(3, 3);

julia> checkbounds(Bool, A, 2)
true

julia> checkbounds(Bool, A, 3, 4)
false

julia> checkbounds(Bool, A, 1:3)
true

julia> checkbounds(Bool, A, 1:3, 2:4)
false
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L618-L644[source] +

----
checkbounds(A, I...)
----

Throw an error if the specified indices `I` are not in bounds for the given array `A`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L661-L665[source] +

[id="Base.checkindex"]
==== *`Base.checkindex`* &mdash; _Function_.

[,julia]
----
checkindex(Bool, inds::AbstractUnitRange, index)
----

Return `true` if the given `index` is within the bounds of `inds`. Custom types that would like to behave as indices for all arrays can extend this method in order to provide a specialized bounds checking implementation.

See also xref:arrays.adoc#Base.checkbounds[`checkbounds`].

*Examples*

[,julia-repl]
----
julia> checkindex(Bool, 1:20, 8)
true

julia> checkindex(Bool, 1:20, 21)
false
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L706-L724[source] +

[id="Base.elsize"]
==== *`Base.elsize`* &mdash; _Function_.

[,julia]
----
elsize(type)
----

Compute the memory stride in bytes between consecutive elements of `eltype` stored inside the given `type`, if the array elements are stored densely with a uniform linear stride.

*Examples*

[,julia-repl]
----
julia> Base.elsize(rand(Float32, 10))
4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L209-L221[source] +

+++<a id="Views-(SubArrays-and-other-view-types)">++++++</a>+++

+++<a id="Views-(SubArrays-and-other-view-types)-1">++++++</a>+++

== Views (SubArrays and other view types)

A "`view`" is a data structure that acts like an array (it is a subtype of `AbstractArray`), but the underlying data is actually part of another array.

For example, if `x` is an array and `v = @view x[1:10]`, then `v` acts like a 10-element array, but its data is actually accessing the first 10 elements of `x`. Writing to a view, e.g. `v[3] = 2`, writes directly to the underlying array `x` (in this case modifying `x[3]`).

Slicing operations like `x[1:10]` create a copy by default in Julia. `@view x[1:10]` changes it to make a view. The `@views` macro can be used on a whole block of code (e.g. `+@views function foo() .... end+` or `+@views begin ... end+`) to change all the slicing operations in that block to use views.  Sometimes making a copy of the data is faster and sometimes using a view is faster, as described in the xref:../manual/performance-tips.adoc#man-performance-views[performance tips].

[id="Base.view"]
==== *`Base.view`* &mdash; _Function_.

[,julia]
----
view(A, inds...)
----

Like xref:collections.adoc#Base.getindex[`getindex`], but returns a lightweight array that lazily references (or is effectively a _view_ into) the parent array `A` at the given index or indices `inds` instead of eagerly extracting elements or constructing a copied subset. Calling xref:collections.adoc#Base.getindex[`getindex`] or xref:collections.adoc#Base.setindex![`setindex!`] on the returned value (often a xref:arrays.adoc#Base.SubArray[`SubArray`]) computes the indices to access or modify the parent array on the fly.  The behavior is undefined if the shape of the parent array is changed after `view` is called because there is no bound check for the parent array; e.g., it may cause a segmentation fault.

Some immutable parent arrays (like ranges) may choose to simply recompute a new array in some circumstances instead of returning a `SubArray` if doing so is efficient and provides compatible semantics.

!!! compat "Julia 1.6"
    In Julia 1.6 or later, `view` can be called on an `AbstractString`, returning a `SubString`.

*Examples*

[,julia-repl]
----
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> b = view(A, :, 1)
2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 1
 3

julia> fill!(b, 0)
2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 0
 0

julia> A # Note A has changed even though we modified b
2×2 Matrix{Int64}:
 0  2
 0  4

julia> view(2:5, 2:3) # returns a range as type is immutable
3:4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/subarray.jl#L128-L173[source] +

[id="Base.@view"]
==== *`Base.@view`* &mdash; _Macro_.

[,julia]
----
@view A[inds...]
----

Transform the indexing expression `+A[inds...]+` into the equivalent xref:arrays.adoc#Base.view[`view`] call.

This can only be applied directly to a single indexing expression and is particularly helpful for expressions that include the special `begin` or `end` indexing syntaxes like `A[begin, 2:end-1]` (as those are not supported by the normal xref:arrays.adoc#Base.view[`view`] function).

Note that `@view` cannot be used as the target of a regular assignment (e.g., `+@view(A[1, 2:end]) = ...+`), nor would the un-decorated xref:../manual/arrays.adoc#man-indexed-assignment[indexed assignment] (`+A[1, 2:end] = ...+`) or broadcasted indexed assignment (`+A[1, 2:end] .= ...+`) make a copy.  It can be useful, however, for _updating_ broadcasted assignments like `@view(A[1, 2:end]) .+= 1` because this is a simple syntax for `@view(A[1, 2:end]) .= @view(A[1, 2:end]) + 1`, and the indexing expression on the right-hand side would otherwise make a copy without the `@view`.

See also xref:arrays.adoc#Base.@views[`@views`] to switch an entire block of code to use views for non-scalar indexing.

!!! compat "Julia 1.5"
    Using `begin` in an indexing expression to refer to the first index requires at least Julia 1.5.

*Examples*

[,julia-repl]
----
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> b = @view A[:, 1]
2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 1
 3

julia> fill!(b, 0)
2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 0
 0

julia> A
2×2 Matrix{Int64}:
 0  2
 0  4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/views.jl#L77-L124[source] +

[id="Base.@views"]
==== *`Base.@views`* &mdash; _Macro_.

[,julia]
----
@views expression
----

Convert every array-slicing operation in the given expression (which may be a `begin`/`end` block, loop, function, etc.) to return a view. Scalar indices, non-array types, and explicit xref:collections.adoc#Base.getindex[`getindex`] calls (as opposed to `+array[...]+`) are unaffected.

!!! note
    The `@views` macro only affects `+array[...]+` expressions that appear explicitly in the given `expression`, not array slicing that occurs in functions called by that code.

!!! compat "Julia 1.5"
    Using `begin` in an indexing expression to refer to the first index requires at least Julia 1.5.

*Examples*

[,julia-repl]
----
julia> A = zeros(3, 3);

julia> @views for row in 1:3
           b = A[row, :]
           b[:] .= row
       end

julia> A
3×3 Matrix{Float64}:
 1.0  1.0  1.0
 2.0  2.0  2.0
 3.0  3.0  3.0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/views.jl#L208-L241[source] +

[id="Base.parent"]
==== *`Base.parent`* &mdash; _Function_.

[,julia]
----
parent(A)
----

Return the underlying "parent array`". This parent array of objects of types `SubArray`, `ReshapedArray` or `LinearAlgebra.Transpose` is what was passed as an argument to `view`, `reshape`, `transpose`, etc. during object creation. If the input is not a wrapped object, return the input itself. If the input is wrapped multiple times, only the outermost wrapper will be removed.

*Examples*

[,julia-repl]
----
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> V = view(A, 1:2, :)
2×2 view(::Matrix{Int64}, 1:2, :) with eltype Int64:
 1  2
 3  4

julia> parent(V)
2×2 Matrix{Int64}:
 1  2
 3  4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L1383-L1408[source] +

[id="Base.parentindices"]
==== *`Base.parentindices`* &mdash; _Function_.

[,julia]
----
parentindices(A)
----

Return the indices in the xref:arrays.adoc#Base.parent[`parent`] which correspond to the array view `A`.

*Examples*

[,julia-repl]
----
julia> A = [1 2; 3 4];

julia> V = view(A, 1, :)
2-element view(::Matrix{Int64}, 1, :) with eltype Int64:
 1
 2

julia> parentindices(V)
(1, Base.Slice(Base.OneTo(2)))
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/subarray.jl#L81-L98[source] +

[id="Base.selectdim"]
==== *`Base.selectdim`* &mdash; _Function_.

[,julia]
----
selectdim(A, d::Integer, i)
----

Return a view of all the data of `A` where the index for dimension `d` equals `i`.

Equivalent to `+view(A,:,:,...,i,:,:,...)+` where `i` is in position `d`.

See also: xref:arrays.adoc#Base.eachslice[`eachslice`].

*Examples*

[,julia-repl]
----
julia> A = [1 2 3 4; 5 6 7 8]
2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

julia> selectdim(A, 2, 3)
2-element view(::Matrix{Int64}, :, 3) with eltype Int64:
 3
 7

julia> selectdim(A, 2, 3:4)
2×2 view(::Matrix{Int64}, :, 3:4) with eltype Int64:
 3  4
 7  8
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L225-L251[source] +

[id="Base.reinterpret"]
==== *`Base.reinterpret`* &mdash; _Function_.

[,julia]
----
reinterpret(type, A)
----

Change the type-interpretation of a block of memory. For arrays, this constructs a view of the array with the same binary data as the given array, but with the specified element type. For example, `reinterpret(Float32, UInt32(7))` interprets the 4 bytes corresponding to `UInt32(7)` as a xref:numbers.adoc#Core.Float32[`Float32`].

*Examples*

[,julia-repl]
----
julia> reinterpret(Float32, UInt32(7))
1.0f-44

julia> reinterpret(Float32, UInt32[1 2 3 4 5])
1×5 reinterpret(Float32, ::Matrix{UInt32}):
 1.0f-45  3.0f-45  4.0f-45  6.0f-45  7.0f-45
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/essentials.jl#L418-L437[source] +

----
reinterpret(reshape, T, A::AbstractArray{S}) -> B
----

Change the type-interpretation of `A` while consuming or adding a "channel dimension."

If `sizeof(T) = n*sizeof(S)` for `n>1`, ``A``'s first dimension must be of size `n` and `B` lacks ``A``'s first dimension. Conversely, if `sizeof(S) = n*sizeof(T)` for `n>1`, `B` gets a new first dimension of size `n`. The dimensionality is unchanged if `sizeof(T) == sizeof(S)`.

!!! compat "Julia 1.6"
    This method requires at least Julia 1.6.

*Examples*

[,julia-repl]
----
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> reinterpret(reshape, Complex{Int}, A)    # the result is a vector
2-element reinterpret(reshape, Complex{Int64}, ::Matrix{Int64}) with eltype Complex{Int64}:
 1 + 3im
 2 + 4im

julia> a = [(1,2,3), (4,5,6)]
2-element Vector{Tuple{Int64, Int64, Int64}}:
 (1, 2, 3)
 (4, 5, 6)

julia> reinterpret(reshape, Int, a)             # the result is a matrix
3×2 reinterpret(reshape, Int64, ::Vector{Tuple{Int64, Int64, Int64}}) with eltype Int64:
 1  4
 2  5
 3  6
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/reinterpretarray.jl#L98-L134[source] +

[id="Base.reshape"]
==== *`Base.reshape`* &mdash; _Function_.

[,julia]
----
reshape(A, dims...) -> AbstractArray
reshape(A, dims) -> AbstractArray
----

Return an array with the same data as `A`, but with different dimension sizes or number of dimensions. The two arrays share the same underlying data, so that the result is mutable if and only if `A` is mutable, and setting elements of one alters the values of the other.

The new dimensions may be specified either as a list of arguments or as a shape tuple. At most one dimension may be specified with a `:`, in which case its length is computed such that its product with all the specified dimensions is equal to the length of the original array `A`. The total number of elements must not change.

*Examples*

[,julia-repl]
----
julia> A = Vector(1:16)
16-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16

julia> reshape(A, (4, 4))
4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

julia> reshape(A, 2, :)
2×8 Matrix{Int64}:
 1  3  5  7   9  11  13  15
 2  4  6  8  10  12  14  16

julia> reshape(1:6, 2, 3)
2×3 reshape(::UnitRange{Int64}, 2, 3) with eltype Int64:
 1  3  5
 2  4  6
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/reshapedarray.jl#L54-L107[source] +

[id="Base.dropdims"]
==== *`Base.dropdims`* &mdash; _Function_.

[,julia]
----
dropdims(A; dims)
----

Return an array with the same data as `A`, but with the dimensions specified by `dims` removed. `size(A,d)` must equal 1 for every `d` in `dims`, and repeated dimensions or numbers outside `1:ndims(A)` are forbidden.

The result shares the same underlying data as `A`, such that the result is mutable if and only if `A` is mutable, and setting elements of one alters the values of the other.

See also: xref:arrays.adoc#Base.reshape[`reshape`], xref:arrays.adoc#Base.vec[`vec`].

*Examples*

[,julia-repl]
----
julia> a = reshape(Vector(1:4),(2,2,1,1))
2×2×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

julia> b = dropdims(a; dims=3)
2×2×1 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

julia> b[1,1,1] = 5; a
2×2×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 5  3
 2  4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L48-L81[source] +

[id="Base.vec"]
==== *`Base.vec`* &mdash; _Function_.

[,julia]
----
vec(a::AbstractArray) -> AbstractVector
----

Reshape the array `a` as a one-dimensional column vector. Return `a` if it is already an `AbstractVector`. The resulting array shares the same underlying data as `a`, so it will only be mutable if `a` is mutable, in which case modifying one will also modify the other.

*Examples*

[,julia-repl]
----
julia> a = [1 2 3; 4 5 6]
2×3 Matrix{Int64}:
 1  2  3
 4  5  6

julia> vec(a)
6-element Vector{Int64}:
 1
 4
 2
 5
 3
 6

julia> vec(1:3)
1:3
----

See also xref:arrays.adoc#Base.reshape[`reshape`], xref:arrays.adoc#Base.dropdims[`dropdims`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L11-L40[source] +

[id="Base.SubArray"]
==== *`Base.SubArray`* &mdash; _Type_.

[,julia]
----
SubArray{T,N,P,I,L} <: AbstractArray{T,N}
----

`N`-dimensional view into a parent array (of type `P`) with an element type `T`, restricted by a tuple of indices (of type `I`). `L` is true for types that support fast linear indexing, and `false` otherwise.

Construct ``SubArray``s using the xref:arrays.adoc#Base.view[`view`] function.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/subarray.jl#L7-L13[source] +

+++<a id="Concatenation-and-permutation">++++++</a>+++

+++<a id="Concatenation-and-permutation-1">++++++</a>+++

== Concatenation and permutation

[id="Base.cat"]
==== *`Base.cat`* &mdash; _Function_.

[,julia]
----
cat(A...; dims)
----

Concatenate the input arrays along the specified dimensions in the iterable `dims`. For dimensions not in `dims`, all input arrays should have the same size, which will also be the size of the output array along that dimension. For dimensions in `dims`, the size of the output array is the sum of the sizes of the input arrays along that dimension. If `dims` is a single number, the different arrays are tightly stacked along that dimension. If `dims` is an iterable containing several dimensions, this allows one to construct block diagonal matrices and their higher-dimensional analogues by simultaneously increasing several dimensions for every new input array and putting zero blocks elsewhere. For example, `+cat(matrices...; dims=(1,2))+` builds a block diagonal matrix, i.e. a block matrix with `matrices[1]`, `matrices[2]`, ... as diagonal blocks and matching zero blocks away from the diagonal.

See also xref:arrays.adoc#Base.hcat[`hcat`], xref:arrays.adoc#Base.vcat[`vcat`], xref:arrays.adoc#Base.hvcat[`hvcat`], xref:arrays.adoc#Base.repeat[`repeat`].

*Examples*

[,julia-repl]
----
julia> cat([1 2; 3 4], [pi, pi], fill(10, 2,3,1); dims=2)
2×6×1 Array{Float64, 3}:
[:, :, 1] =
 1.0  2.0  3.14159  10.0  10.0  10.0
 3.0  4.0  3.14159  10.0  10.0  10.0

julia> cat(true, trues(2,2), trues(4)', dims=(1,2))
4×7 Matrix{Bool}:
 1  0  0  0  0  0  0
 0  1  1  0  0  0  0
 0  1  1  0  0  0  0
 0  0  0  1  1  1  1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L1883-L1915[source] +

[id="Base.vcat"]
==== *`Base.vcat`* &mdash; _Function_.

[,julia]
----
vcat(A...)
----

Concatenate along dimension 1. To efficiently concatenate a large vector of arrays, use `reduce(vcat, x)`.

*Examples*

[,julia-repl]
----
julia> a = [1 2 3 4 5]
1×5 Matrix{Int64}:
 1  2  3  4  5

julia> b = [6 7 8 9 10; 11 12 13 14 15]
2×5 Matrix{Int64}:
  6   7   8   9  10
 11  12  13  14  15

julia> vcat(a,b)
3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

julia> c = ([1 2 3], [4 5 6])
([1 2 3], [4 5 6])

julia> vcat(c...)
2×3 Matrix{Int64}:
 1  2  3
 4  5  6

julia> vs = [[1, 2], [3, 4], [5, 6]]
3-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]
 [5, 6]

julia> reduce(vcat, vs)
6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L1768-L1814[source] +

[id="Base.hcat"]
==== *`Base.hcat`* &mdash; _Function_.

[,julia]
----
hcat(A...)
----

Concatenate along dimension 2. To efficiently concatenate a large vector of arrays, use `reduce(hcat, x)`.

*Examples*

[,julia-repl]
----
julia> a = [1; 2; 3; 4; 5]
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> b = [6 7; 8 9; 10 11; 12 13; 14 15]
5×2 Matrix{Int64}:
  6   7
  8   9
 10  11
 12  13
 14  15

julia> hcat(a,b)
5×3 Matrix{Int64}:
 1   6   7
 2   8   9
 3  10  11
 4  12  13
 5  14  15

julia> c = ([1; 2; 3], [4; 5; 6])
([1, 2, 3], [4, 5, 6])

julia> hcat(c...)
3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

julia> x = Matrix(undef, 3, 0)  # x = [] would have created an Array{Any, 1}, but need an Array{Any, 2}
3×0 Matrix{Any}

julia> hcat(x, [1; 2; 3])
3×1 Matrix{Any}:
 1
 2
 3

julia> vs = [[1, 2], [3, 4], [5, 6]]
3-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]
 [5, 6]

julia> reduce(hcat, vs)
2×3 Matrix{Int64}:
 1  3  5
 2  4  6
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L1816-L1877[source] +

[id="Base.hvcat"]
==== *`Base.hvcat`* &mdash; _Function_.

[,julia]
----
hvcat(rows::Tuple{Vararg{Int}}, values...)
----

Horizontal and vertical concatenation in one call. This function is called for block matrix syntax. The first argument specifies the number of arguments to concatenate in each block row.

*Examples*

[,julia-repl]
----
julia> a, b, c, d, e, f = 1, 2, 3, 4, 5, 6
(1, 2, 3, 4, 5, 6)

julia> [a b c; d e f]
2×3 Matrix{Int64}:
 1  2  3
 4  5  6

julia> hvcat((3,3), a,b,c,d,e,f)
2×3 Matrix{Int64}:
 1  2  3
 4  5  6

julia> [a b; c d; e f]
3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

julia> hvcat((2,2,2), a,b,c,d,e,f)
3×2 Matrix{Int64}:
 1  2
 3  4
 5  6
----

If the first argument is a single integer `n`, then all block rows are assumed to have `n` block columns.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L1951-L1988[source] +

[id="Base.hvncat"]
==== *`Base.hvncat`* &mdash; _Function_.

[,julia]
----
hvncat(dim::Int, row_first, values...)
hvncat(dims::Tuple{Vararg{Int}}, row_first, values...)
hvncat(shape::Tuple{Vararg{Tuple}}, row_first, values...)
----

Horizontal, vertical, and n-dimensional concatenation of many `values` in one call.

This function is called for block matrix syntax. The first argument either specifies the shape of the concatenation, similar to `hvcat`, as a tuple of tuples, or the dimensions that specify the key number of elements along each axis, and is used to determine the output dimensions. The `dims` form is more performant, and is used by default when the concatenation operation has the same number of elements along each axis (e.g., [a b; c d;;; e f ; g h]). The `shape` form is used when the number of elements along each axis is unbalanced (e.g., [a b ; c]). Unbalanced syntax needs additional validation overhead. The `dim` form is an optimization for concatenation along just one dimension. `row_first` indicates how `values` are ordered. The meaning of the first and second elements of `shape` are also swapped based on `row_first`.

*Examples*

[,julia-repl]
----
julia> a, b, c, d, e, f = 1, 2, 3, 4, 5, 6
(1, 2, 3, 4, 5, 6)

julia> [a b c;;; d e f]
1×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3

[:, :, 2] =
 4  5  6

julia> hvncat((2,1,3), false, a,b,c,d,e,f)
2×1×3 Array{Int64, 3}:
[:, :, 1] =
 1
 2

[:, :, 2] =
 3
 4

[:, :, 3] =
 5
 6

julia> [a b;;; c d;;; e f]
1×2×3 Array{Int64, 3}:
[:, :, 1] =
 1  2

[:, :, 2] =
 3  4

[:, :, 3] =
 5  6

julia> hvncat(((3, 3), (3, 3), (6,)), true, a, b, c, d, e, f)
1×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3

[:, :, 2] =
 4  5  6
----

*Examples for construction of the arguments:*

[,julia]
----
[a b c ; d e f ;;;
 g h i ; j k l ;;;
 m n o ; p q r ;;;
 s t u ; v w x]
=> dims = (2, 3, 4)

[a b ; c ;;; d ;;;;]
 ___   _     _
 2     1     1 = elements in each row (2, 1, 1)
 _______     _
 3           1 = elements in each column (3, 1)
 _____________
 4             = elements in each 3d slice (4,)
 _____________
 4             = elements in each 4d slice (4,)
 => shape = ((2, 1, 1), (3, 1), (4,), (4,)) with `rowfirst` = true
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L2102-L2187[source] +

[id="Base.vect"]
==== *`Base.vect`* &mdash; _Function_.

[,julia]
----
vect(X...)
----

Create a xref:arrays.adoc#Base.Vector[`Vector`] with element type computed from the `promote_typeof` of the argument, containing the argument list.

*Examples*

[,julia-repl]
----
julia> a = Base.vect(UInt8(1), 2.5, 1//2)
3-element Vector{Float64}:
 1.0
 2.5
 0.5
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L128-L142[source] +

[id="Base.circshift"]
==== *`Base.circshift`* &mdash; _Function_.

[,julia]
----
circshift(A, shifts)
----

Circularly shift, i.e. rotate, the data in an array. The second argument is a tuple or vector giving the amount to shift in each dimension, or an integer to shift only in the first dimension.

See also: xref:arrays.adoc#Base.circshift![`circshift!`], xref:arrays.adoc#Base.circcopy![`circcopy!`], xref:math.adoc#Base.bitrotate[`bitrotate`], xref:math.adoc#Base.:<<[`<<`].

*Examples*

[,julia-repl]
----
julia> b = reshape(Vector(1:16), (4,4))
4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

julia> circshift(b, (0,2))
4×4 Matrix{Int64}:
  9  13  1  5
 10  14  2  6
 11  15  3  7
 12  16  4  8

julia> circshift(b, (-1,0))
4×4 Matrix{Int64}:
 2  6  10  14
 3  7  11  15
 4  8  12  16
 1  5   9  13

julia> a = BitArray([true, true, false, false, true])
5-element BitVector:
 1
 1
 0
 0
 1

julia> circshift(a, 1)
5-element BitVector:
 1
 1
 1
 0
 0

julia> circshift(a, -1)
5-element BitVector:
 1
 0
 0
 1
 1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L264-L320[source] +

[id="Base.circshift!"]
==== *`Base.circshift!`* &mdash; _Function_.

[,julia]
----
circshift!(dest, src, shifts)
----

Circularly shift, i.e. rotate, the data in `src`, storing the result in `dest`. `shifts` specifies the amount to shift in each dimension.

The `dest` array must be distinct from the `src` array (they cannot alias each other).

See also xref:arrays.adoc#Base.circshift[`circshift`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/multidimensional.jl#L1162-L1172[source] +

[id="Base.circcopy!"]
==== *`Base.circcopy!`* &mdash; _Function_.

[,julia]
----
circcopy!(dest, src)
----

Copy `src` to `dest`, indexing each dimension modulo its length. `src` and `dest` must have the same size, but can be offset in their indices; any offset results in a (circular) wraparound. If the arrays have overlapping indices, then on the domain of the overlap `dest` agrees with `src`.

See also: xref:arrays.adoc#Base.circshift[`circshift`].

*Examples*

[,julia-repl]
----
julia> src = reshape(Vector(1:16), (4,4))
4×4 Array{Int64,2}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

julia> dest = OffsetArray{Int}(undef, (0:3,2:5))

julia> circcopy!(dest, src)
OffsetArrays.OffsetArray{Int64,2,Array{Int64,2}} with indices 0:3×2:5:
 8  12  16  4
 5   9  13  1
 6  10  14  2
 7  11  15  3

julia> dest[1:3,2:4] == src[1:3,2:4]
true
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/multidimensional.jl#L1218-L1250[source] +

[id="Base.findall-Tuple{Any}"]
==== *`Base.findall`* &mdash; _Method_.

[,julia]
----
findall(A)
----

Return a vector `I` of the `true` indices or keys of `A`. If there are no such elements of `A`, return an empty array. To search for other kinds of values, pass a predicate as the first argument.

Indices or keys are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

See also: xref:arrays.adoc#Base.findfirst-Tuple{Any}[`findfirst`], xref:sort.adoc#Base.Sort.searchsorted[`searchsorted`].

*Examples*

[,julia-repl]
----
julia> A = [true, false, false, true]
4-element Vector{Bool}:
 1
 0
 0
 1

julia> findall(A)
2-element Vector{Int64}:
 1
 4

julia> A = [true false; false true]
2×2 Matrix{Bool}:
 1  0
 0  1

julia> findall(A)
2-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 2)

julia> findall(falses(3))
Int64[]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L2313-L2352[source] +

[id="Base.findall-Tuple{Function, Any}"]
==== *`Base.findall`* &mdash; _Method_.

[,julia]
----
findall(f::Function, A)
----

Return a vector `I` of the indices or keys of `A` where `f(A[I])` returns `true`. If there are no such elements of `A`, return an empty array.

Indices or keys are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

*Examples*

[,julia-repl]
----
julia> x = [1, 3, 4]
3-element Vector{Int64}:
 1
 3
 4

julia> findall(isodd, x)
2-element Vector{Int64}:
 1
 2

julia> A = [1 2 0; 3 4 0]
2×3 Matrix{Int64}:
 1  2  0
 3  4  0
julia> findall(isodd, A)
2-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)

julia> findall(!iszero, A)
4-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(1, 2)
 CartesianIndex(2, 2)

julia> d = Dict(:A => 10, :B => -1, :C => 0)
Dict{Symbol, Int64} with 3 entries:
  :A => 10
  :B => -1
  :C => 0

julia> findall(x -> x >= 0, d)
2-element Vector{Symbol}:
 :A
 :C
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L2256-L2306[source] +

[id="Base.findfirst-Tuple{Any}"]
==== *`Base.findfirst`* &mdash; _Method_.

[,julia]
----
findfirst(A)
----

Return the index or key of the first `true` value in `A`. Return `nothing` if no such value is found. To search for other kinds of values, pass a predicate as the first argument.

Indices or keys are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

See also: xref:arrays.adoc#Base.findall-Tuple{Any}[`findall`], xref:arrays.adoc#Base.findnext-Tuple{Any, Integer}[`findnext`], xref:arrays.adoc#Base.findlast-Tuple{Any}[`findlast`], xref:sort.adoc#Base.Sort.searchsortedfirst[`searchsortedfirst`].

*Examples*

[,julia-repl]
----
julia> A = [false, false, true, false]
4-element Vector{Bool}:
 0
 0
 1
 0

julia> findfirst(A)
3

julia> findfirst(falses(3)) # returns nothing, but not printed in the REPL

julia> A = [false false; true false]
2×2 Matrix{Bool}:
 0  0
 1  0

julia> findfirst(A)
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L1954-L1988[source] +

[id="Base.findfirst-Tuple{Function, Any}"]
==== *`Base.findfirst`* &mdash; _Method_.

[,julia]
----
findfirst(predicate::Function, A)
----

Return the index or key of the first element of `A` for which `predicate` returns `true`. Return `nothing` if there is no such element.

Indices or keys are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

*Examples*

[,julia-repl]
----
julia> A = [1, 4, 2, 2]
4-element Vector{Int64}:
 1
 4
 2
 2

julia> findfirst(iseven, A)
2

julia> findfirst(x -> x>10, A) # returns nothing, but not printed in the REPL

julia> findfirst(isequal(4), A)
2

julia> A = [1 4; 2 2]
2×2 Matrix{Int64}:
 1  4
 2  2

julia> findfirst(iseven, A)
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L2031-L2065[source] +

[id="Base.findlast-Tuple{Any}"]
==== *`Base.findlast`* &mdash; _Method_.

[,julia]
----
findlast(A)
----

Return the index or key of the last `true` value in `A`. Return `nothing` if there is no `true` value in `A`.

Indices or keys are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

See also: xref:arrays.adoc#Base.findfirst-Tuple{Any}[`findfirst`], xref:arrays.adoc#Base.findprev-Tuple{Any, Integer}[`findprev`], xref:arrays.adoc#Base.findall-Tuple{Any}[`findall`].

*Examples*

[,julia-repl]
----
julia> A = [true, false, true, false]
4-element Vector{Bool}:
 1
 0
 1
 0

julia> findlast(A)
3

julia> A = falses(2,2);

julia> findlast(A) # returns nothing, but not printed in the REPL

julia> A = [true false; true false]
2×2 Matrix{Bool}:
 1  0
 1  0

julia> findlast(A)
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L2127-L2162[source] +

[id="Base.findlast-Tuple{Function, Any}"]
==== *`Base.findlast`* &mdash; _Method_.

[,julia]
----
findlast(predicate::Function, A)
----

Return the index or key of the last element of `A` for which `predicate` returns `true`. Return `nothing` if there is no such element.

Indices or keys are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

*Examples*

[,julia-repl]
----
julia> A = [1, 2, 3, 4]
4-element Vector{Int64}:
 1
 2
 3
 4

julia> findlast(isodd, A)
3

julia> findlast(x -> x > 5, A) # returns nothing, but not printed in the REPL

julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> findlast(isodd, A)
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L2213-L2244[source] +

[id="Base.findnext-Tuple{Any, Integer}"]
==== *`Base.findnext`* &mdash; _Method_.

[,julia]
----
findnext(A, i)
----

Find the next index after or including `i` of a `true` element of `A`, or `nothing` if not found.

Indices are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

*Examples*

[,julia-repl]
----
julia> A = [false, false, true, false]
4-element Vector{Bool}:
 0
 0
 1
 0

julia> findnext(A, 1)
3

julia> findnext(A, 4) # returns nothing, but not printed in the REPL

julia> A = [false false; true false]
2×2 Matrix{Bool}:
 0  0
 1  0

julia> findnext(A, CartesianIndex(1, 1))
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L1920-L1951[source] +

[id="Base.findnext-Tuple{Function, Any, Integer}"]
==== *`Base.findnext`* &mdash; _Method_.

[,julia]
----
findnext(predicate::Function, A, i)
----

Find the next index after or including `i` of an element of `A` for which `predicate` returns `true`, or `nothing` if not found.

Indices are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

*Examples*

[,julia-repl]
----
julia> A = [1, 4, 2, 2];

julia> findnext(isodd, A, 1)
1

julia> findnext(isodd, A, 2) # returns nothing, but not printed in the REPL

julia> A = [1 4; 2 2];

julia> findnext(isodd, A, CartesianIndex(1, 1))
CartesianIndex(1, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L1994-L2017[source] +

[id="Base.findprev-Tuple{Any, Integer}"]
==== *`Base.findprev`* &mdash; _Method_.

[,julia]
----
findprev(A, i)
----

Find the previous index before or including `i` of a `true` element of `A`, or `nothing` if not found.

Indices are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

See also: xref:arrays.adoc#Base.findnext-Tuple{Any, Integer}[`findnext`], xref:arrays.adoc#Base.findfirst-Tuple{Any}[`findfirst`], xref:arrays.adoc#Base.findall-Tuple{Any}[`findall`].

*Examples*

[,julia-repl]
----
julia> A = [false, false, true, true]
4-element Vector{Bool}:
 0
 0
 1
 1

julia> findprev(A, 3)
3

julia> findprev(A, 1) # returns nothing, but not printed in the REPL

julia> A = [false false; true true]
2×2 Matrix{Bool}:
 0  0
 1  1

julia> findprev(A, CartesianIndex(2, 1))
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L2091-L2124[source] +

[id="Base.findprev-Tuple{Function, Any, Integer}"]
==== *`Base.findprev`* &mdash; _Method_.

[,julia]
----
findprev(predicate::Function, A, i)
----

Find the previous index before or including `i` of an element of `A` for which `predicate` returns `true`, or `nothing` if not found.

Indices are of the same type as those returned by xref:arrays.adoc#Base.keys-Tuple{AbstractArray}[`keys(A)`] and xref:collections.adoc#Base.pairs[`pairs(A)`].

*Examples*

[,julia-repl]
----
julia> A = [4, 6, 1, 2]
4-element Vector{Int64}:
 4
 6
 1
 2

julia> findprev(isodd, A, 1) # returns nothing, but not printed in the REPL

julia> findprev(isodd, A, 3)
3

julia> A = [4 6; 1 2]
2×2 Matrix{Int64}:
 4  6
 1  2

julia> findprev(isodd, A, CartesianIndex(1, 2))
CartesianIndex(2, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L2168-L2199[source] +

[id="Base.permutedims"]
==== *`Base.permutedims`* &mdash; _Function_.

[,julia]
----
permutedims(A::AbstractArray, perm)
----

Permute the dimensions of array `A`. `perm` is a vector or a tuple of length `ndims(A)` specifying the permutation.

See also xref:arrays.adoc#Base.permutedims![`permutedims!`], xref:arrays.adoc#Base.PermutedDimsArrays.PermutedDimsArray[`PermutedDimsArray`], xref:../stdlib/LinearAlgebra.adoc#Base.transpose[`transpose`], xref:arrays.adoc#Base.invperm[`invperm`].

*Examples*

[,julia-repl]
----
julia> A = reshape(Vector(1:8), (2,2,2))
2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

julia> permutedims(A, (3, 2, 1))
2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  3
 5  7

[:, :, 2] =
 2  4
 6  8

julia> B = randn(5, 7, 11, 13);

julia> perm = [4,1,3,2];

julia> size(permutedims(B, perm))
(13, 5, 11, 7)

julia> size(B)[perm] == ans
true
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/permuteddimsarray.jl#L83-L123[source] +

----
permutedims(m::AbstractMatrix)
----

Permute the dimensions of the matrix `m`, by flipping the elements across the diagonal of the matrix. Differs from ``LinearAlgebra``'s xref:../stdlib/LinearAlgebra.adoc#Base.transpose[`transpose`] in that the operation is not recursive.

*Examples*

[,julia-repl]
----
julia> a = [1 2; 3 4];

julia> b = [5 6; 7 8];

julia> c = [9 10; 11 12];

julia> d = [13 14; 15 16];

julia> X = [[a] [b]; [c] [d]]
2×2 Matrix{Matrix{Int64}}:
 [1 2; 3 4]     [5 6; 7 8]
 [9 10; 11 12]  [13 14; 15 16]

julia> permutedims(X)
2×2 Matrix{Matrix{Int64}}:
 [1 2; 3 4]  [9 10; 11 12]
 [5 6; 7 8]  [13 14; 15 16]

julia> transpose(X)
2×2 transpose(::Matrix{Matrix{Int64}}) with eltype Transpose{Int64, Matrix{Int64}}:
 [1 3; 2 4]  [9 11; 10 12]
 [5 7; 6 8]  [13 15; 14 16]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/permuteddimsarray.jl#L129-L161[source] +

----
permutedims(v::AbstractVector)
----

Reshape vector `v` into a `1 × length(v)` row matrix. Differs from ``LinearAlgebra``'s xref:../stdlib/LinearAlgebra.adoc#Base.transpose[`transpose`] in that the operation is not recursive.

*Examples*

[,julia-repl]
----
julia> permutedims([1, 2, 3, 4])
1×4 Matrix{Int64}:
 1  2  3  4

julia> V = [[[1 2; 3 4]]; [[5 6; 7 8]]]
2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [5 6; 7 8]

julia> permutedims(V)
1×2 Matrix{Matrix{Int64}}:
 [1 2; 3 4]  [5 6; 7 8]

julia> transpose(V)
1×2 transpose(::Vector{Matrix{Int64}}) with eltype Transpose{Int64, Matrix{Int64}}:
 [1 3; 2 4]  [5 7; 6 8]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/permuteddimsarray.jl#L164-L190[source] +

[id="Base.permutedims!"]
==== *`Base.permutedims!`* &mdash; _Function_.

[,julia]
----
permutedims!(dest, src, perm)
----

Permute the dimensions of array `src` and store the result in the array `dest`. `perm` is a vector specifying a permutation of length `ndims(src)`. The preallocated array `dest` should have `size(dest) == size(src)[perm]` and is completely overwritten. No in-place permutation is supported and unexpected results will happen if `src` and `dest` have overlapping memory regions.

See also xref:arrays.adoc#Base.permutedims[`permutedims`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/permuteddimsarray.jl#L193-L203[source] +

[id="Base.PermutedDimsArrays.PermutedDimsArray"]
==== *`Base.PermutedDimsArrays.PermutedDimsArray`* &mdash; _Type_.

[,julia]
----
PermutedDimsArray(A, perm) -> B
----

Given an AbstractArray `A`, create a view `B` such that the dimensions appear to be permuted. Similar to `permutedims`, except that no copying occurs (`B` shares storage with `A`).

See also xref:arrays.adoc#Base.permutedims[`permutedims`], xref:arrays.adoc#Base.invperm[`invperm`].

*Examples*

[,julia-repl]
----
julia> A = rand(3,5,4);

julia> B = PermutedDimsArray(A, (3,1,2));

julia> size(B)
(4, 3, 5)

julia> B[3,1,2] == A[1,2,3]
true
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/permuteddimsarray.jl#L20-L41[source] +

[id="Base.promote_shape"]
==== *`Base.promote_shape`* &mdash; _Function_.

[,julia]
----
promote_shape(s1, s2)
----

Check two array shapes for compatibility, allowing trailing singleton dimensions, and return whichever shape has more dimensions.

*Examples*

[,julia-repl]
----
julia> a = fill(1, (3,4,1,1,1));

julia> b = fill(1, (3,4));

julia> promote_shape(a,b)
(Base.OneTo(3), Base.OneTo(4), Base.OneTo(1), Base.OneTo(1), Base.OneTo(1))

julia> promote_shape((2,3,1,4), (2, 3, 1, 4, 1))
(2, 3, 1, 4, 1)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/indices.jl#L132-L150[source] +

+++<a id="Array-functions">++++++</a>+++

+++<a id="Array-functions-1">++++++</a>+++

== Array functions

[id="Base.accumulate"]
==== *`Base.accumulate`* &mdash; _Function_.

[,julia]
----
accumulate(op, A; dims::Integer, [init])
----

Cumulative operation `op` along the dimension `dims` of `A` (providing `dims` is optional for vectors). An initial value `init` may optionally be provided by a keyword argument. See also xref:arrays.adoc#Base.accumulate![`accumulate!`] to use a preallocated output array, both for performance and to control the precision of the output (e.g. to avoid overflow).

For common operations there are specialized variants of `accumulate`, see xref:arrays.adoc#Base.cumsum[`cumsum`], xref:arrays.adoc#Base.cumprod[`cumprod`]. For a lazy version, see xref:iterators.adoc#Base.Iterators.accumulate[`Iterators.accumulate`].

!!! compat "Julia 1.5"
    `accumulate` on a non-array iterator requires at least Julia 1.5.

*Examples*

[,julia-repl]
----
julia> accumulate(+, [1,2,3])
3-element Vector{Int64}:
 1
 3
 6

julia> accumulate(min, (1, -2, 3, -4, 5), init=0)
(0, -2, -2, -4, -4)

julia> accumulate(/, (2, 4, Inf), init=100)
(50.0, 12.5, 0.0)

julia> accumulate(=>, i^2 for i in 1:3)
3-element Vector{Any}:
          1
        1 => 4
 (1 => 4) => 9

julia> accumulate(+, fill(1, 3, 4))
3×4 Matrix{Int64}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

julia> accumulate(+, fill(1, 2, 5), dims=2, init=100.0)
2×5 Matrix{Float64}:
 101.0  102.0  103.0  104.0  105.0
 101.0  102.0  103.0  104.0  105.0
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L225-L271[source] +

[id="Base.accumulate!"]
==== *`Base.accumulate!`* &mdash; _Function_.

[,julia]
----
accumulate!(op, B, A; [dims], [init])
----

Cumulative operation `op` on `A` along the dimension `dims`, storing the result in `B`. Providing `dims` is optional for vectors.  If the keyword argument `init` is given, its value is used to instantiate the accumulation.

See also xref:arrays.adoc#Base.accumulate[`accumulate`], xref:arrays.adoc#Base.cumsum![`cumsum!`], xref:arrays.adoc#Base.cumprod![`cumprod!`].

*Examples*

[,julia-repl]
----
julia> x = [1, 0, 2, 0, 3];

julia> y = rand(5);

julia> accumulate!(+, y, x);

julia> y
5-element Vector{Float64}:
 1.0
 1.0
 3.0
 3.0
 6.0

julia> A = [1 2 3; 4 5 6];

julia> B = similar(A);

julia> accumulate!(-, B, A, dims=1)
2×3 Matrix{Int64}:
  1   2   3
 -3  -3  -3

julia> accumulate!(*, B, A, dims=2, init=10)
2×3 Matrix{Int64}:
 10   20    60
 40  200  1200
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L297-L336[source] +

[id="Base.cumprod"]
==== *`Base.cumprod`* &mdash; _Function_.

[,julia]
----
cumprod(A; dims::Integer)
----

Cumulative product along the dimension `dim`. See also xref:arrays.adoc#Base.cumprod![`cumprod!`] to use a preallocated output array, both for performance and to control the precision of the output (e.g. to avoid overflow).

*Examples*

[,julia-repl]
----
julia> a = Int8[1 2 3; 4 5 6];

julia> cumprod(a, dims=1)
2×3 Matrix{Int64}:
 1   2   3
 4  10  18

julia> cumprod(a, dims=2)
2×3 Matrix{Int64}:
 1   2    6
 4  20  120
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L165-L186[source] +

----
cumprod(itr)
----

Cumulative product of an iterator.

See also xref:arrays.adoc#Base.cumprod![`cumprod!`], xref:arrays.adoc#Base.accumulate[`accumulate`], xref:arrays.adoc#Base.cumsum[`cumsum`].

!!! compat "Julia 1.5"
    `cumprod` on a non-array iterator requires at least Julia 1.5.

*Examples*

[,julia-repl]
----
julia> cumprod(fill(1//2, 3))
3-element Vector{Rational{Int64}}:
 1//2
 1//4
 1//8

julia> cumprod((1, 2, 1, 3, 1))
(1, 2, 2, 6, 6)

julia> cumprod("julia")
5-element Vector{String}:
 "j"
 "ju"
 "jul"
 "juli"
 "julia"
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L191-L220[source] +

[id="Base.cumprod!"]
==== *`Base.cumprod!`* &mdash; _Function_.

[,julia]
----
cumprod!(B, A; dims::Integer)
----

Cumulative product of `A` along the dimension `dims`, storing the result in `B`. See also xref:arrays.adoc#Base.cumprod[`cumprod`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L148-L153[source] +

----
cumprod!(y::AbstractVector, x::AbstractVector)
----

Cumulative product of a vector `x`, storing the result in `y`. See also xref:arrays.adoc#Base.cumprod[`cumprod`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L157-L162[source] +

[id="Base.cumsum"]
==== *`Base.cumsum`* &mdash; _Function_.

[,julia]
----
cumsum(A; dims::Integer)
----

Cumulative sum along the dimension `dims`. See also xref:arrays.adoc#Base.cumsum![`cumsum!`] to use a preallocated output array, both for performance and to control the precision of the output (e.g. to avoid overflow).

*Examples*

[,julia-repl]
----
julia> a = [1 2 3; 4 5 6]
2×3 Matrix{Int64}:
 1  2  3
 4  5  6

julia> cumsum(a, dims=1)
2×3 Matrix{Int64}:
 1  2  3
 5  7  9

julia> cumsum(a, dims=2)
2×3 Matrix{Int64}:
 1  3   6
 4  9  15
----

!!! note
    The return array's `eltype` is `Int` for signed integers of less than system word size  and `UInt` for unsigned integers of less than system word size. To preserve `eltype` of arrays with small signed or unsigned integer `accumulate(+, A)` should be used.

....
```julia-repl
julia> cumsum(Int8[100, 28])
2-element Vector{Int64}:
 100
 128

julia> accumulate(+,Int8[100, 28])
2-element Vector{Int8}:
  100
 -128
```

In the former case, the integers are widened to system word size and therefore the result is `Int64[100, 128]`. In the latter case, no such widening happens and integer overflow results in `Int8[100, -128]`.
....

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L64-L110[source] +

----
cumsum(itr)
----

Cumulative sum of an iterator.

See also xref:arrays.adoc#Base.accumulate[`accumulate`] to apply functions other than `+`.

!!! compat "Julia 1.5"
    `cumsum` on a non-array iterator requires at least Julia 1.5.

*Examples*

[,julia-repl]
----
julia> cumsum(1:3)
3-element Vector{Int64}:
 1
 3
 6

julia> cumsum((true, false, true, false, true))
(1, 1, 2, 2, 3)

julia> cumsum(fill(1, 2) for i in 1:3)
3-element Vector{Vector{Int64}}:
 [1, 1]
 [2, 2]
 [3, 3]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L116-L143[source] +

[id="Base.cumsum!"]
==== *`Base.cumsum!`* &mdash; _Function_.

[,julia]
----
cumsum!(B, A; dims::Integer)
----

Cumulative sum of `A` along the dimension `dims`, storing the result in `B`. See also xref:arrays.adoc#Base.cumsum[`cumsum`].

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/accumulate.jl#L41-L45[source] +

[id="Base.diff"]
==== *`Base.diff`* &mdash; _Function_.

[,julia]
----
diff(A::AbstractVector)
diff(A::AbstractArray; dims::Integer)
----

Finite difference operator on a vector or a multidimensional array `A`. In the latter case the dimension to operate on needs to be specified with the `dims` keyword argument.

!!! compat "Julia 1.1"
    `diff` for arrays with dimension higher than 2 requires at least Julia 1.1.

*Examples*

[,julia-repl]
----
julia> a = [2 4; 6 16]
2×2 Matrix{Int64}:
 2   4
 6  16

julia> diff(a, dims=2)
2×1 Matrix{Int64}:
  2
 10

julia> diff(vec(a))
3-element Vector{Int64}:
  4
 -2
 12
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/multidimensional.jl#L967-L996[source] +

[id="Base.repeat"]
==== *`Base.repeat`* &mdash; _Function_.

[,julia]
----
repeat(A::AbstractArray, counts::Integer...)
----

Construct an array by repeating array `A` a given number of times in each dimension, specified by `counts`.

See also: xref:arrays.adoc#Base.fill[`fill`], xref:iterators.adoc#Base.Iterators.repeated[`Iterators.repeated`], xref:iterators.adoc#Base.Iterators.cycle[`Iterators.cycle`].

*Examples*

[,julia-repl]
----
julia> repeat([1, 2, 3], 2)
6-element Vector{Int64}:
 1
 2
 3
 1
 2
 3

julia> repeat([1, 2, 3], 2, 3)
6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 3  3  3
 1  1  1
 2  2  2
 3  3  3
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L327-L354[source] +

----
repeat(A::AbstractArray; inner=ntuple(Returns(1), ndims(A)), outer=ntuple(Returns(1), ndims(A)))
----

Construct an array by repeating the entries of `A`. The i-th element of `inner` specifies the number of times that the individual entries of the i-th dimension of `A` should be repeated. The i-th element of `outer` specifies the number of times that a slice along the i-th dimension of `A` should be repeated. If `inner` or `outer` are omitted, no repetition is performed.

*Examples*

[,julia-repl]
----
julia> repeat(1:2, inner=2)
4-element Vector{Int64}:
 1
 1
 2
 2

julia> repeat(1:2, outer=2)
4-element Vector{Int64}:
 1
 2
 1
 2

julia> repeat([1 2; 3 4], inner=(2, 1), outer=(1, 3))
4×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 3  4  3  4  3  4
 3  4  3  4  3  4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L359-L391[source] +

[,julia]
----
repeat(s::AbstractString, r::Integer)
----

Repeat a string `r` times. This can be written as `+s^r+`.

See also xref:strings.adoc#Base.:^-Tuple{Union{AbstractChar, AbstractString}, Integer}[`^`].

*Examples*

[,julia-repl]
----
julia> repeat("ha", 3)
"hahaha"
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/strings/basic.jl#L702-L714[source] +

[,julia]
----
repeat(c::AbstractChar, r::Integer) -> String
----

Repeat a character `r` times. This can equivalently be accomplished by calling xref:strings.adoc#Base.:^-Tuple{Union{AbstractChar, AbstractString}, Integer}[`+c^r+`].

*Examples*

[,julia-repl]
----
julia> repeat('A', 3)
"AAA"
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/strings/string.jl#L325-L336[source] +

[id="Base.rot180"]
==== *`Base.rot180`* &mdash; _Function_.

[,julia]
----
rot180(A)
----

Rotate matrix `A` 180 degrees.

*Examples*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> rot180(a)
2×2 Matrix{Int64}:
 4  3
 2  1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L158-L175[source] +

----
rot180(A, k)
----

Rotate matrix `A` 180 degrees an integer `k` number of times. If `k` is even, this is equivalent to a `copy`.

*Examples*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> rot180(a,1)
2×2 Matrix{Int64}:
 4  3
 2  1

julia> rot180(a,2)
2×2 Matrix{Int64}:
 1  2
 3  4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L260-L283[source] +

[id="Base.rotl90"]
==== *`Base.rotl90`* &mdash; _Function_.

[,julia]
----
rotl90(A)
----

Rotate matrix `A` left 90 degrees.

*Examples*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> rotl90(a)
2×2 Matrix{Int64}:
 2  4
 1  3
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L103-L120[source] +

----
rotl90(A, k)
----

Left-rotate matrix `A` 90 degrees counterclockwise an integer `k` number of times. If `k` is a multiple of four (including zero), this is equivalent to a `copy`.

*Examples*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> rotl90(a,1)
2×2 Matrix{Int64}:
 2  4
 1  3

julia> rotl90(a,2)
2×2 Matrix{Int64}:
 4  3
 2  1

julia> rotl90(a,3)
2×2 Matrix{Int64}:
 3  1
 4  2

julia> rotl90(a,4)
2×2 Matrix{Int64}:
 1  2
 3  4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L185-L218[source] +

[id="Base.rotr90"]
==== *`Base.rotr90`* &mdash; _Function_.

[,julia]
----
rotr90(A)
----

Rotate matrix `A` right 90 degrees.

*Examples*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> rotr90(a)
2×2 Matrix{Int64}:
 3  1
 4  2
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L131-L148[source] +

----
rotr90(A, k)
----

Right-rotate matrix `A` 90 degrees clockwise an integer `k` number of times. If `k` is a multiple of four (including zero), this is equivalent to a `copy`.

*Examples*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> rotr90(a,1)
2×2 Matrix{Int64}:
 3  1
 4  2

julia> rotr90(a,2)
2×2 Matrix{Int64}:
 4  3
 2  1

julia> rotr90(a,3)
2×2 Matrix{Int64}:
 2  4
 1  3

julia> rotr90(a,4)
2×2 Matrix{Int64}:
 1  2
 3  4
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L225-L258[source] +

[id="Base.mapslices"]
==== *`Base.mapslices`* &mdash; _Function_.

[,julia]
----
mapslices(f, A; dims)
----

Transform the given dimensions of array `A` using function `f`. `f` is called on each slice of `A` of the form `+A[...,:,...,:,...]+`. `dims` is an integer vector specifying where the colons go in this expression. The results are concatenated along the remaining dimensions. For example, if `dims` is `[1,2]` and `A` is 4-dimensional, `f` is called on `A[:,:,i,j]` for all `i` and `j`.

See also xref:arrays.adoc#Base.eachcol[`eachcol`], xref:arrays.adoc#Base.eachslice[`eachslice`].

*Examples*

[,julia-repl]
----
julia> a = reshape(Vector(1:16),(2,2,2,2))
2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

julia> mapslices(sum, a, dims = [1,2])
1×1×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 10

[:, :, 2, 1] =
 26

[:, :, 1, 2] =
 42

[:, :, 2, 2] =
 58
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarray.jl#L2782-L2827[source] +

[id="Base.eachrow"]
==== *`Base.eachrow`* &mdash; _Function_.

[,julia]
----
eachrow(A::AbstractVecOrMat)
----

Create a generator that iterates over the first dimension of vector or matrix `A`, returning the rows as `AbstractVector` views.

See also xref:arrays.adoc#Base.eachcol[`eachcol`], xref:arrays.adoc#Base.eachslice[`eachslice`], xref:arrays.adoc#Base.mapslices[`mapslices`].

!!! compat "Julia 1.1"
    This function requires at least Julia 1.1.

*Example*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> first(eachrow(a))
2-element view(::Matrix{Int64}, 1, :) with eltype Int64:
 1
 2

julia> collect(eachrow(a))
2-element Vector{SubArray{Int64, 1, Matrix{Int64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}}:
 [1, 2]
 [3, 4]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L520-L549[source] +

[id="Base.eachcol"]
==== *`Base.eachcol`* &mdash; _Function_.

[,julia]
----
eachcol(A::AbstractVecOrMat)
----

Create a generator that iterates over the second dimension of matrix `A`, returning the columns as `AbstractVector` views.

See also xref:arrays.adoc#Base.eachrow[`eachrow`] and xref:arrays.adoc#Base.eachslice[`eachslice`].

!!! compat "Julia 1.1"
    This function requires at least Julia 1.1.

*Example*

[,julia-repl]
----
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> first(eachcol(a))
2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 1
 3

julia> collect(eachcol(a))
2-element Vector{SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}}:
 [1, 3]
 [2, 4]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L553-L582[source] +

[id="Base.eachslice"]
==== *`Base.eachslice`* &mdash; _Function_.

[,julia]
----
eachslice(A::AbstractArray; dims)
----

Create a generator that iterates over dimensions `dims` of `A`, returning views that select all the data from the other dimensions in `A`.

Only a single dimension in `dims` is currently supported. Equivalent to `+(view(A,:,:,...,i,:,: ...)) for i in axes(A, dims))+`, where `i` is in position `dims`.

See also xref:arrays.adoc#Base.eachrow[`eachrow`], xref:arrays.adoc#Base.eachcol[`eachcol`], xref:arrays.adoc#Base.mapslices[`mapslices`], and xref:arrays.adoc#Base.selectdim[`selectdim`].

!!! compat "Julia 1.1"
    This function requires at least Julia 1.1.

*Example*

[,julia-repl]
----
julia> M = [1 2 3; 4 5 6; 7 8 9]
3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

julia> first(eachslice(M, dims=1))
3-element view(::Matrix{Int64}, 1, :) with eltype Int64:
 1
 2
 3

julia> collect(eachslice(M, dims=2))
3-element Vector{SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}}:
 [1, 4, 7]
 [2, 5, 8]
 [3, 6, 9]
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/abstractarraymath.jl#L585-L620[source] +

+++<a id="Combinatorics">++++++</a>+++

+++<a id="Combinatorics-1">++++++</a>+++

== Combinatorics

[id="Base.invperm"]
==== *`Base.invperm`* &mdash; _Function_.

[,julia]
----
invperm(v)
----

Return the inverse permutation of `v`. If `B = A[v]`, then `A == B[invperm(v)]`.

See also xref:sort.adoc#Base.sortperm[`sortperm`], xref:arrays.adoc#Base.invpermute![`invpermute!`], xref:arrays.adoc#Base.isperm[`isperm`], xref:arrays.adoc#Base.permutedims[`permutedims`].

*Examples*

[,julia-repl]
----
julia> p = (2, 3, 1);

julia> invperm(p)
(3, 1, 2)

julia> v = [2; 4; 3; 1];

julia> invperm(v)
4-element Vector{Int64}:
 4
 1
 3
 2

julia> A = ['a','b','c','d'];

julia> B = A[v]
4-element Vector{Char}:
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

julia> B[invperm(v)]
4-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/combinatorics.jl#L237-L277[source] +

[id="Base.isperm"]
==== *`Base.isperm`* &mdash; _Function_.

[,julia]
----
isperm(v) -> Bool
----

Return `true` if `v` is a valid permutation.

*Examples*

[,julia-repl]
----
julia> isperm([1; 2])
true

julia> isperm([1; 3])
false
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/combinatorics.jl#L55-L68[source] +

[id="Base.permute!-Tuple{Any, AbstractVector}"]
==== *`Base.permute!`* &mdash; _Method_.

[,julia]
----
permute!(v, p)
----

Permute vector `v` in-place, according to permutation `p`. No checking is done to verify that `p` is a permutation.

To return a new permutation, use `v[p]`. Note that this is generally faster than `permute!(v,p)` for large vectors.

See also xref:arrays.adoc#Base.invpermute![`invpermute!`].

*Examples*

[,julia-repl]
----
julia> A = [1, 1, 3, 4];

julia> perm = [2, 4, 3, 1];

julia> permute!(A, perm);

julia> A
4-element Vector{Int64}:
 1
 4
 3
 1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/combinatorics.jl#L161-L187[source] +

[id="Base.invpermute!"]
==== *`Base.invpermute!`* &mdash; _Function_.

[,julia]
----
invpermute!(v, p)
----

Like xref:arrays.adoc#Base.permute!-Tuple{Any, AbstractVector}[`permute!`], but the inverse of the given permutation is applied.

*Examples*

[,julia-repl]
----
julia> A = [1, 1, 3, 4];

julia> perm = [2, 4, 3, 1];

julia> invpermute!(A, perm);

julia> A
4-element Vector{Int64}:
 4
 1
 3
 1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/combinatorics.jl#L214-L234[source] +

[id="Base.reverse-Tuple{AbstractVector}"]
==== *`Base.reverse`* &mdash; _Method_.

[,julia]
----
reverse(A; dims=:)
----

Reverse `A` along dimension `dims`, which can be an integer (a single dimension), a tuple of integers (a tuple of dimensions) or `:` (reverse along all the dimensions, the default).  See also xref:arrays.adoc#Base.reverse![`reverse!`] for in-place reversal.

*Examples*

[,julia-repl]
----
julia> b = Int64[1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> reverse(b, dims=2)
2×2 Matrix{Int64}:
 2  1
 4  3

julia> reverse(b)
2×2 Matrix{Int64}:
 4  3
 2  1
----

!!! compat "Julia 1.6"
    Prior to Julia 1.6, only single-integer `dims` are supported in `reverse`.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L30-L58[source] +

[id="Base.reverseind"]
==== *`Base.reverseind`* &mdash; _Function_.

[,julia]
----
reverseind(v, i)
----

Given an index `i` in xref:arrays.adoc#Base.reverse-Tuple{AbstractVector}[`reverse(v)`], return the corresponding index in `v` so that `v[reverseind(v,i)] == reverse(v)[i]`. (This can be nontrivial in cases where `v` contains non-ASCII characters.)

*Examples*

[,julia-repl]
----
julia> s = "Julia🚀"
"Julia🚀"

julia> r = reverse(s)
"🚀ailuJ"

julia> for i in eachindex(s)
           print(r[reverseind(r, i)])
       end
Julia🚀
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/strings/basic.jl#L679-L699[source] +

[id="Base.reverse!"]
==== *`Base.reverse!`* &mdash; _Function_.

[,julia]
----
reverse!(v [, start=1 [, stop=length(v) ]]) -> v
----

In-place version of xref:arrays.adoc#Base.reverse-Tuple{AbstractVector}[`reverse`].

*Examples*

[,julia-repl]
----
julia> A = Vector(1:5)
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> reverse!(A);

julia> A
5-element Vector{Int64}:
 5
 4
 3
 2
 1
----

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/array.jl#L1841-L1866[source] +

----
reverse!(A; dims=:)
----

Like xref:arrays.adoc#Base.reverse-Tuple{AbstractVector}[`reverse`], but operates in-place in `A`.

!!! compat "Julia 1.6"
    Multidimensional `reverse!` requires Julia 1.6.

https://github.com/JuliaLang/julia/blob/17cfb8e65ead377bf1b4598d8a9869144142c84e/base/arraymath.jl#L62-L69[source] +
