== Interfaces

A lot of the power and extensibility in Julia comes from a collection of
informal interfaces. By extending a few specific methods to work for a
custom type, objects of that type not only receive those
functionalities, but they are also able to be used in other methods that
are written to generically build upon those behaviors.

Тестовая ссылка: xref:getting-started.adoc#_resources[_resources]

=== Iteration

[width="100%",cols="<15%,<10%,<75%",options="header",]
|===
|Required methods | |Brief description
|`iterate(iter)` | |Returns either a tuple of the first item and initial
state or xref:base/constants.adoc#Core.nothing[`nothing`] if empty

|`iterate(iter, state)` | |Returns either a tuple of the next item and
next state or `nothing` if no items remain

|*Important optional methods* |*Default definition* |*Brief description*

|`Base.IteratorSize(IterType)` |`Base.HasLength()` |One of
`Base.HasLength()`, `Base.HasShape{N}()`, `Base.IsInfinite()`, or
`Base.SizeUnknown()` as appropriate

|`Base.IteratorEltype(IterType)` |`Base.HasEltype()` |Either
`Base.EltypeUnknown()` or `Base.HasEltype()` as appropriate

|`eltype(IterType)` |`Any` |The type of the first entry of the tuple
returned by `iterate()`

|`length(iter)` |(_undefined_) |The number of items, if known

|`size(iter, [dim])` |(_undefined_) |The number of items in each
dimension, if known

|`Base.isdone(iter[, state])` |`missing` |Fast-path hint for iterator
completion. Should be defined for mutable iterators, or else
`isempty(iter)` will call `iterate(iter[, state])` and may mutate the
iterator.
|===

[width="100%",cols="<39%,<61%",options="header",]
|===
|Value returned by `IteratorSize(IterType)` |Required Methods
|`Base.HasLength()`
|xref:base/arrays.adoc#Base.length-Tuple%7BAbstractArray%7D[`length(iter)`]

|`Base.HasShape{N}()` |`length(iter)` and `size(iter, [dim])`

|`Base.IsInfinite()` |(_none_)

|`Base.SizeUnknown()` |(_none_)
|===

[cols="<,<",options="header",]
|===
|Value returned by `IteratorEltype(IterType)` |Required Methods
|`Base.HasEltype()` |`eltype(IterType)`
|`Base.EltypeUnknown()` |(_none_)
|===

Sequential iteration is implemented by the
xref:base:collections.adoc#Base.iterate[`iterate`] function. Instead of
mutating objects as they are iterated over, Julia iterators may keep
track of the iteration state externally from the object. The return
value from iterate is always either a tuple of a value and a state, or
`nothing` if no elements remain. The state object will be passed back to
the iterate function on the next iteration and is generally considered
an implementation detail private to the iterable object.
