:doctype: book

+++<a id="man-variables">++++++</a>+++

+++<a id="man-variables-1">++++++</a>+++

= Переменные

Переменная в языке Julia - это имя, ассоциированное (или связанное) с некоторым значением. Переменные нужны в случаях, когда вы хотите сохранить значение (которое вы получили, например, в результате вычислений) для последующего использования. Например:

[,julia-repl]
----
# Присвоить переменной x значение 10
julia> x = 10
10

# Производим вычисления со значением x
julia> x + 1
11

# Переписать значение x
julia> x = 1 + 1
2

# Вы можете присваивать переменным значения других типов, например текстовые строки
julia> x = "Hello World!"
"Hello World!"
----

Система именования переменных в Julia очень гибкая. Имена переменных чувствительны к регистру, и у них нет семантических ограничений (то есть, Julia не будет обрабатывать переменные по-разному в зависимости от их имен).

[,julia-repl]
----
julia> x = 1.0
1.0

julia> y = -3
-3

julia> Z = "My string"
"My string"

julia> customary_phrase = "Hello world!"
"Hello world!"

julia> UniversalDeclarationOfHumanRightsStart = "人人生而自由，在尊严和权利上一律平等。"
"人人生而自由，在尊严和权利上一律平等。"
----

Разрешены имена в Unicode (в кодировке UTF-8):

[,julia-repl]
----
julia> δ = 0.00001
1.0e-5

julia> 안녕하세요 = "Hello"
"Hello"
----

В Julia REPL и во многих других средах можно вводить математические символы Unicode через имя символа в LaTeX, при этом перед ним ставится обратный слэш, а после него - tab. Например, можно ввести имя переменной `δ`, набрав `\delta`-_tab_, и даже имя `α̂⁽²⁾` - набрав `\alpha`-_tab_-`\hat`- _tab_-`+\^(2)+`-_tab_. (Если где-то, например, в чьем-то коде, вам встретился символ и вы не знаете, как его набрать, то вам поможет справка REPL: просто введите `?` и вставьте этот символ.)

В Julia при необходимости можно даже переопределять значения встроенных констант и функций (хотя это и не рекомендуется во избежание возможных недоразумений):

[,julia-repl]
----
julia> pi = 3
3

julia> pi
3

julia> sqrt = 4
4
----

Однако если попытаться переопределить встроенную константу или функцию, которая уже используется, Julia выдаст ошибку:

[,julia-repl]
----
julia> pi
π = 3.1415926535897...

julia> pi = 3
ERROR: cannot assign a value to variable MathConstants.pi from module Main
ОШИБКА: невозможно присвоить значение переменной MathConstants.pi из модуля Main

julia> sqrt(100)
10.0

julia> sqrt = 4
ERROR: cannot assign a value to variable Base.sqrt from module Main
ОШИБКА: невозможно присвоить значение переменной Base.sqrt из модуля Main
----

+++<a id="man-allowed-variable-names">++++++</a>+++

+++<a id="man-allowed-variable-names-1">++++++</a>+++

== Разрешенные имена переменных

Имена переменных должны начинаться с буквы (A-Z или a-z), символа подчеркивания или символа Unicode, чей код больше 00A0; в частности разрешены следующие https://www.fileformat.info/info/unicode/category/index.htm[категории символов Unicode]: Lu/Ll/Lt/Lm/Lo/Nl (буквы), Sc/So (валюты и другие символы) и некоторые другие категории, подобные буквам (например, Sm math). Начиная со второго символа может также использоваться ! или цифры (0-9 и другие символы из категорий Nd/No) и другие символы Unicode: диакритики и прочие модифицирующие символы (категории Mn/Mc/Me/Sk), некоторые пунктуационные коннекторы (категория Pc), штрихи и несколько других символов.

Операторы, такие как `+`, тоже являются идентификаторами, но обрабатываются специальным образом. В некоторых контекстах операторы могут использоваться так же, как переменные; например, `(+)` обозначает функцию сложения, а запись `(+) = f` переопределит это значение. Большинство инфиксных операторов Unicode (из категории Sm), например, `⊕`, обрабатываются как инфиксные операторы, и их можно использовать для методов, определяемых пользователем (например, можно использовать запись `const ⊗ = kron`, чтобы определить `⊕` как инфиксный оператор для произведения Кронекера). К операторам также можно добавлять модифицирующие символы, штрихи и текст в нижнем или верхнем индексах, например, `+̂ₐ″` будет обработан как инфиксный оператор с тем же приоритетом, что и у `+`. Между оператором с текстом в нижнем или верхнем индексах и следующим за ним именем переменной необходимо ставить пробел. Например, если `+ᵃ` - это оператор, то `+ᵃx` следует записывать в виде `+ᵃ x`, чтобы эта запись отличалась от `+ ᵃx`, где `ᵃx` является именем переменной.

Отдельный класс имен переменных образуют имена, состоящие только из символов подчеркивания.  Этим идентификаторам можно присвоить значение, но их нельзя использовать для присвоения значений другим переменным. Говоря более формально, они могут использоваться только в качестве https://en.wikipedia.org/wiki/Value_(computer_science)#lrvalue[l-значений], но не в качестве https://en.wikipedia.org/wiki/R-value[`r-значений`]:

[,julia-repl]
----
julia> x, ___ = size([2 2; 1 1])
(2, 2)

julia> y = ___
ERROR: syntax: all-underscore identifier used as rvalue
ОШИБКА: синтаксис: идентификатор, состоящий только из символов подчеркивания, использован в качестве r-значения
----

В качестве имен переменных на прямую запрещены только имена встроенных xref:base:base.adoc#Keywords[Ключевых слов]:

[,julia-repl]
----
julia> else = false
ERROR: syntax: unexpected "else"
ОШИБКА: синтаксис: не ожидается "else"

julia> try = "No"
ERROR: syntax: unexpected "="
ОШИБКА: синтаксис: не ожидается "="
----

Некоторые символы Unicode в именах идентификаторов считаются эквивалентными. Разные способы ввода комбинируемых символов Unicode (например, акцентов) признаются эквивалентными (другими словами, идентификаторы в Julia нормализованы по http://www.macchiato.com/unicode/nfc-faq[NFC]). В Julia также есть несколько нестандартных случаев эквивалентности визуально близких символов, которые могут быть легко введены несколькими способами. Символы Unicode `ɛ` (U+025B: латинский строчный эпсилон) и `µ` (U+00B5: символ "микро") считаются эквивалентными соответствующим греческим буквам. Точка по центру `·` (U+00B7) и греческий https://en.wikipedia.org/wiki/Interpunct[интерпункт] `·` (U+0387) оба считаются эквивалентными математическому оператору умножения `⋅` (U+22C5). Символ минус `−` (U+2212) признается эквивалентным символу дефис-минус `-` (U+002D).

+++<a id="Stylistic-Conventions">++++++</a>+++

+++<a id="Stylistic-Conventions-1">++++++</a>+++

== Стилистические конвенции

Несмотря на то, что в Julia мало ограничений на валидные имена переменных, считается полезным придерживаться следующих конвенций:

* Для имен переменных используется нижний регистр.
* Границы слов могут обозначаться символами подчеркивания (`'_'`),  но использование подчеркиваний рекомендуется только в случаях, когда имя сложно прочитать без них.
* Имена типов (`Type`) и модулей (`Module`) начинаются с заглавной буквы, а границы слов обозначаются через UpperCamelCase вместо подчеркиваний.
* Имена функций (`function`) и макросов (`macro`) задаются в нижнем регистре без подчеркиваний.
* Имена функций, которые изменяют свои аргументы, заканчиваются на `!`. Их иногда называют модифицирующими ("mutating") функциями или функциями "in-place", так как они производят изменения в своих аргументах после вызова, а не просто возвращают значение.

Подробнее о стилистических конвенциях можно узнать в xref:style-guide.adoc#Style-Guide[Style Guide].

+++<a id="Тесты-ссылок">++++++</a>+++

+++<a id="Тесты-ссылок-1">++++++</a>+++

== Тесты ссылок

Construct an uninitialized `N`-dimensional xref:base:arrays.adoc#Core.Array[`Array`] containing elements of type `T`.

Construct an uninitialized `N`-dimensional xref:base:arrays.adoc#Core.Array[`Массив`] containing elements of type `T`.

Construct an uninitialized `N`-dimensional xref:base:arrays.adoc#Core.Array[`Массив`] containing elements of type `T`.

Ссылка через полное имя с сигнатурой: xref:base:arrays.adoc#Core.Array-Tuple{UndefInitializer, Any}[`+Array{T}(undef, dims)+`]

Ссылка через неполное имя с сигнатурой: xref:base:arrays.adoc#Core.Array-Tuple{UndefInitializer, Any}[`+Array{T}(undef, dims)+`]

Ссылка через заголовок раздела:  xref:base:math.adoc#Base.:--Tuple{Any, Any}[`+Array{T}(undef, dims)+`]

Ссылка на xref:style-guide.adoc#Style-Guide[Стайл гайд]

Ссылка на xref:variables.adoc#Stylistic-Conventions[Стилистические конвенции]

Ссылка на xref:variables.adoc#Stylistic-Conventions[Stylistic Conventions]

Ссылка на xref:base:collections.adoc#Base.IteratorSize[`HasShape`]
