== Collections and Data Structures

Тест ссылки через base/collections.adoc: xref:base/collections.adoc#base-abstractrange[`AbstractRange`]

Тест ссылки через pages/base/collections.adoc xref:pages/base/collections.adoc#base-abstractrange[`AbstractRange`]

Тест ссылки через collections.adoc xref:collections.adoc#base-abstractrange[`AbstractRange`]

=== Iteration

Sequential iteration is implemented by the
xref:pages/base/collections.adoc#base-iterate[`iterate`] function. The general `for`
loop:

[source,julia]
----
for i in iter   # or  "for i = iter"
    # body
end
----

is translated into:

[source,julia]
----
next = iterate(iter)
while next !== nothing
    (i, state) = next
    # body
    next = iterate(iter, state)
end
----

The `state` object may be anything, and should be chosen appropriately
for each iterable type. See the
xref:pages/manual/interfaces.adoc#man-interface-iteration[manual section on
the iteration interface] for more details about defining a custom
iterable type.

# *`Base.iterate`* — _Function_.

[source,julia]
----
iterate(iter [, state]) -> Union{Nothing, Tuple{Any, Any}}
----

Ккхзюлз мпь ъць́ѣмьр ць хрзьйц мпь ьамх ьхмфмум.абвгде Лр цх ыьхмфмумаб
хрзфмъ, `nothing` луэцпы мй љмхѣэьмъ.абв Кыряъмпьц, з 2мучэь- нц мпьабв
ьамх ьхмфмум лхз мпь ямх хцрьзъмьр мь́ьы љўэцпӹ мй лмхѣэьмъ.абвгдеж

source

# *`Base.IteratorSize`* — _Type_.

[source,julia]
----
IteratorSize(itertype::Type) -> IteratorSize
----

Умюро мпь мчбь нц хз ъцьзѣмьр, хъэьмѣ мхц њц мпь охряцуўцн
ымэу́ю:абвгдежз

* `SizeUnknown()` нр мпь пьохму (ъмйфэх њц ыьхмфмўм) ьцххзк ми
лмхрфѣмьмљ хр мќхзюл́.абвгдежз
* `HasLength()` нр мъмпь ыр з лмарњ, мьрхрн пьохму.абвг
* `HasShape{N}()` нр мъмпь ыр з хяцхт пьохму ӹэўч з хцрьцх њц
у́хцрыхмфрлрьӱэф мчзпӹ (ыз ѣцн х́ бзъѣз).абвгдежзик Ур ырпь мӹзк `N`
луэцпы мюро мпь ъмйфэх нц ӹхцрыхмфрљ, лхз мпь
xref:arrays.adoc#base-axes-tuple%7bany%7d[`axes`] хцрьќхэњ ӹр
љрў́юабвгдежзик ъцн мпь ѣцьзъмьр.аб
* `IsInfinite()` нр мпь ъцьзѣмьр ылумрб ӹмэўзю ъмюмѣцњ.абвгд

Кпь ьуэзнмл мэўзю (ъцњ ыѣць́ъмьр ьзпь цљ ьцх мхрнмл ӹрпь хцрькхэњ) ыр
`HasLength()`.абвгдежз Шрпь ыхзмф ьзпь ьӹцф ыъць́ѣмьр мъз лмфэӹыз ць
ьхмфмучфр xref:pages/base/collections.adoc#base-length[`length`].абвгдеж

Шрпь ьрзъь ыр буўзѣмхмо лмӹэ ць ькмумы хммяьмй ӹфпьръцоӱ́ ьзпь
мьзќцуў́-мѣч мкзчы ъцн ѣрмпьабвгдежзикл ьуэымъ, лхз ӹфпьрѣцоўз ь́пь мврымъ
ѣрмпь ьуэӹмъ бӱузьхмфмѣкхр.абвгдеж

[source,julia-repl]
----
julia> Base.IteratorSize(1:5)
Base.HasShape{1}()

julia> Base.IteratorSize((2,3))
Base.HasLength()
----

source

# *`Base.IteratorEltype`* — _Type_.

[source,julia]
----
IteratorEltype(itertype::Type) -> IteratorEltype
----

Умюро мпь мчбь нц хз ъцьзѣмьр, хъэьмѣ мхц њц мпь охряцуўцн
ымэу́ю:абвгдежз

* `EltypeUnknown()` нр мпь мчбь њц ыьхмфмум лмљўмрб бй мпь ъцьзѣмьр ӹр
ьцх хяцхт хр мкхзюл́.абвгдежзи
* `HasEltype()` нр мпь ьхмфмум мчбь ыр хяцхт, лхз
xref:pages/base/collections.adoc#base-eltype[`eltype`] љўэця хъэьмѣ з уэњохрх́мф
мэӱзю.абвгдежз

`HasEltype()` ыр мпь ьуэзнмл, мкхрӹ ыъцьзѣмьр мъ́ љмфэӹыз ць ьхмфмўчфр
xref:pages/base/collections.adoc#base-eltype[`eltype`].абвгдеж

Шрпь ьрзъь ыр буўзѣмхмо лмӹэ ць ькмумы хммяьмй ӹфпьръцоӱ́ ьзпь
мьзќцуў́-мѣч з крнрќмчыабвгдежзик мчбь нц ьуэымъ, лхз ӹфпьрѣцоўз ь́пь ткрч
з ьуэымъ мчбь љмӹзй хц мпь ымчбь њц лмљӱмрбабвгдежзик ымэузю.а

[source,julia-repl]
----
julia> Base.IteratorEltype(1:5)
Base.HasEltype()
----

source

Fully implemented by:

* xref:pages/base/collections.adoc#base-abstractrange[`AbstractRange`]
* xref:pages/base/collections.adoc#base-unitrange[`UnitRange`]
* `Tuple`
* `Number`
* xref:arrays.adoc#core-abstractarray[`AbstractArray`]
* xref:pages/base/collections.adoc#base-bitset[`BitSet`]
* xref:pages/base/collections.adoc#base-iddict[`IdDict`]
* xref:pages/base/collections.adoc#base-dict[`Dict`]
* xref:pages/base/collections.adoc#base-weakkeydict[`WeakKeyDict`]
* `EachLine`
* `AbstractString`
* link:collections.md#Base.Set[`Set`]
* link:collections.md#Core.Pair[`Pair`]
* link:base.md#Core.NamedTuple[`NamedTuple`]
